Zoom features
Unact/yandex_mapkit pull request #116
Opened 2021-07-02 18:18 UTC by cream-cheeze

Additional zoom features:

- disable/enable zoom gestures;
- get zoom gestures enabled status;
- get min/max zoom.

2021-07-21 15:11 UTC, gevork commented
Any news on this pull request?

2021-07-21 18:03 UTC, cream-cheeze commented
Waiting for @DCrow to review.

2021-07-22 08:11 UTC, DCrow requested changes
Спасибо за доработку!

Пару моментов надо поправить перед мерджем

2021-07-22 09:34 UTC, cream-cheeze commented on lib/src/yandex_map_controller.dart
> +  Future<void> setZoomGesturesEnabled({required bool enabled}) async {
Думал об этом, когда делал, но посчитал, что текущие названия неоднозначны, поэтому сделал по своему. Например, toggleMapRotation (как и в случае с zoomGestures и tiltGestures) отключает именно жесты, чего не следует из названия - это не означает, что карту нельзя будет повернуть или масштабировать программно. К тому же конструкция с "set" ближе к нативным методам – как мне кажется, это важно, потому что помогает легче строить аналогии между документацией mapkit и функционалом плагина.
Если принципиально - сделаю toggle, но тогда уж лучше toggleZoomGesturesEnabled.

2021-07-22 09:38 UTC, cream-cheeze commented on example/lib/examples/map_controls_page.dart
> +              var zoomGesturesEnabled = await controller!.isZoomGesturesEnabled();
Нет, но это является примером получения информации о текущем состоянии опции из контроллера - по умолчанию значение установлено в false, но при загрузке карты оно устанавливается в текущее состояние опции карты (по умолчанию - true), по чему можно судить, что isZoomGesturesEnabled() работает.

2021-07-22 10:11 UTC, cream-cheeze commented on example/lib/examples/map_controls_page.dart
> +              print('Map rendered');
Готово

2021-07-22 10:11 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +      case "isZoomGesturesEnabled":
Исправил, спасибо.

2021-07-22 10:12 UTC, cream-cheeze commented on lib/src/yandex_map_controller.dart
> +  Future<void> setZoomGesturesEnabled({required bool enabled}) async {
Готово

2021-07-22 10:21 UTC, cream-cheeze commented on lib/src/yandex_map_controller.dart
> +  Future<void> setZoomGesturesEnabled({required bool enabled}) async {
Только сейчас увидел комментарии к соседнему PR (tilt_gestures).
Давайте тогда так:
- toggleZoomGestures 
- toggleTiltGestures

Сейчас здесь ещё поправлю - уберу Enabled на конце.

2021-07-22 10:35 UTC, cream-cheeze commented on lib/src/yandex_map_controller.dart
> +  Future<void> setZoomGesturesEnabled({required bool enabled}) async {
Готово

2021-07-22 10:35 UTC, cream-cheeze commented
Правки внёс.

2021-07-22 10:54 UTC, DCrow commented on example/lib/examples/map_controls_page.dart
> +              var zoomGesturesEnabled = await controller!.isZoomGesturesEnabled();
Да тогда получается наглядный пример.

2021-07-22 11:01 UTC, merged