#34 basic driving router
Unact/yandex_mapkit pull request #118
Opened 2021-07-05 09:37 UTC by ILAgent

Поправил замечания предыдущего пр, проме того, что касается интерфейса метода построения маршута. Я всё же считаю, что использвовать Future правильнее, чем придумывать свой интерфейс калбека.

2021-07-22 09:15 UTC, DCrow requested changes
Спасибо за доработку!

Оставил комменты по моментам, которые нашел в этом PR, с прошлым вроде все замечания поправлены.

С использование Future, вместо калбэков все же не соглашусь. 
Особенно видно это в обработчиках ошибок, где из-за того что результат может быть в двух вариантах(безошибочное выполнение и ошибочное), везде обрабатывается только безошибочное, а ошибочное через try/catch приходится. 
Обработка результатов выполнения в YandexSearchHandler все же более удобная для пользователя.
Кроме того остаются все моменты, которые в прошлом PR перечислял.

2021-07-22 09:15 UTC, DCrow commented on lib/src/yandex_driving_router.dart
> +        .invokeListMethod<dynamic>('requestRoutes', request)
Что-то тут вообще плохо читается в редакторе.

Не совсем понятно зачем использовать `invokeListMethod`, если можно того же эффекта добится с помощью `invokeMethod<List<dynamic>>`
Кроме того в методе ошибки приходящие со стороны iOS никак не обрабатываются.

2021-07-22 09:15 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexDrivingRouterHandlerImpl.java
> +                        result.error("onDrivingRoutesError", null, null);
Получается, что пользователь не может указать handler для этого рода ошибок, только через try/catch, что все же должно использоваться для исключений(не предвиденных ошибок), а тут вполне возможная ситуация. 
Надо давать пользователям явно задавать обработчика ошибок.

2021-07-22 12:27 UTC, ILAgent commented on example/lib/examples/router_page.dart
> +                          } catch (_) {}
Ещё в случае, если забудешь задать клбч мапкита, например. Но можно убрать, да.

2021-07-22 12:29 UTC, ILAgent commented on example/android/app/build.gradle
> +    compileSdkVersion 30
У меня не собирается, если не поднять версию грэдла. К тому же это сэмпл, не сама либа, думаю не очень критинчо, в каком пр.

2021-07-22 12:33 UTC, ILAgent commented on lib/src/yandex_driving_router.dart
> +        .invokeListMethod<dynamic>('requestRoutes', request)
>Что-то тут вообще плохо читается в редакторе.

Да, dartfmt форматирует код так себе(

>Не совсем понятно зачем использовать invokeListMethod, если можно того же эффекта добится с помощью invokeMethod<List<dynamic>>

Почему нет?) Он как раз для этого, не?

>Кроме того в методе ошибки приходящие со стороны iOS никак не обрабатываются.

Ты про onError в лиснере?

2021-07-22 12:34 UTC, ILAgent commented on example/lib/examples/router_page.dart
> +                            await _controller?.removePolyline(_route!);
да, можно late сделать

2021-07-22 12:36 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexDrivingRouterHandlerImpl.java
> +                        result.error("onDrivingRoutesError", null, null);
Как вариант, можно делать `result.success(null)`. Всё равно какой-то инфы об ошибке предоставлять не предполагается.

2021-07-22 20:03 UTC, ILAgent commented
>Особенно видно это в обработчиках ошибок, где из-за того что результат может быть в двух вариантах(безошибочное выполнение и ошибочное), везде обрабатывается только безошибочное, а ошибочное через try/catch приходится.

В данном случае соглашусь с тем, что не надо кидать ошибку в onError - либо возвращать null в этом случае, либо инфу об ошибке через отдельное поле объекта-результата. 

>Обработка результатов выполнения в YandexSearchHandler все же более удобная для пользователя.

Если бы калбеки были удобны, не стали бы изобретать промисы, таски, фьючерсы, async/await и прочие корутины :) Калбеки используются в языках, где нет современных средств работы с асинхронным кодом -  в Java, например. 

 >Кроме того остаются все моменты, которые в прошлом PR перечислял.
 
Я там ответил на них)

Скажи, будешь мёржить, если я всё остальное поправлю? Т.е. останется тут так же, только в onError будем возвращать null вместо списка маршрутов, а не кидать ошибку.

2021-07-23 07:24 UTC, DCrow commented on example/lib/examples/router_page.dart
> +                          } catch (_) {}
Так если забудешь задать, то ошибку уж точно не надо ловить. 
Также никогда не узнаешь что она была...

2021-07-23 07:25 UTC, DCrow commented on example/lib/examples/router_page.dart
> +                            await _controller?.removePolyline(_route!);
late для этого случая не подходит, так как во время построения widget во flutter, _controller вполне может быть null, а вот в действиях кнопок мы уверены, что он не null. 
Все же это пример для других разработчиков, а не самостоятельное приложение, поэтому надо писать в рекомендуемом формате.

2021-07-23 07:27 UTC, DCrow commented on example/android/app/build.gradle
> +    compileSdkVersion 30
Не, значит тут что-то не так, если со старой версией не работает. 
Апдейты любых версий это отдельная задача, не надо смешивать разные задачи.

2021-07-23 07:29 UTC, DCrow commented on lib/src/yandex_driving_router.dart
> +        .invokeListMethod<dynamic>('requestRoutes', request)
> Почему нет?) Он как раз для этого, не?

В целом тут смысл в поддерживании кода, нет необходимости использовать разные методы, которые имеют похожий смысл, если в этом нет особенной необходимости.

> Ты про onError в лиснере?

Что-то я не понял о чем ты. В swift коде ничего такого не увидел

2021-07-23 07:33 UTC, DCrow commented
Как я в прошлом PR говорил
> Кроме того плохо иметь разные имплементации одних и тех же действий(в данном случае это различие с YandexSearchHandlerImpl).
Это в дальнейшем и усложняет поддержку, и начинает путать других пользователей либы, которые видят это впервые.

Поэтому пока они будут различаться, я не могу смерджить этот PR. 
Кроме того работа с `YandexDrivingRouter` получается сильно отличающейся от работы с остальной части либы(в части каллбэков)

2021-07-23 07:37 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexDrivingRouterHandlerImpl.java
> +                        result.error("onDrivingRoutesError", null, null);
Надо иметь различные методы для успешного выполнения и ошибочного. 
На много удобнее иметь возможность обрабатывать успешные результаты в одном методе, а ошибочные в другом, не задумываясь о том какой ответ пришел. 

В твоем случае это перекладывается на пользователя либы, ему придется каждый раз проверять, что за ответ пришел. Зачем ему жизнь усложнять?

2021-07-23 07:42 UTC, ILAgent commented
Так же только в поиске сейчас? Давай переделаем?

2021-07-23 07:58 UTC, DCrow commented
Сейчас только в поиске, но опять же в варианте, который ты предлагаешь, нет способа нормально обработать ошибки(см. https://github.com/Unact/yandex_mapkit/pull/118#discussion_r675363811)
Это очень хорошо решается, если использовать калбэки.

Кроме того есть другой PR, который кардинально меняет поиск, причем оставляет тот же вариант с калбэками.

2021-07-23 20:23 UTC, ILAgent commented
>Сейчас только в поиске, но опять же в варианте, который ты предлагаешь, нет способа нормально обработать ошибки

Нормально - это как? По возможностям future и калбеки вообще ничем не отличаются. На Future тоже можно подписывать калбеками (метод then), но зачем? asyn/await  более удобно и канонично в Дарте. 

Насчёт поиска. Сейчас там нет калбека для ошибки и в случае ошибки просто сбрасывается сессия. Т.е. пользователь будет бесконечно ждать результата и не узнает об ошибке. Это стоит поправить.

>Кроме того есть другой PR #119, который кардинально меняет поиск, причем оставляет тот же вариант с калбэками.

Ещё не поздно поправить)

2021-07-26 08:09 UTC, DCrow commented
> Нормально - это как? По возможностям future и калбеки вообще ничем не отличаются. На Future тоже можно подписывать калбеками (метод then), но зачем? asyn/await более удобно и канонично в Дарте.

Я имел ввиду через калбэки, чтобы можно было задать onSuccess, onError функции. 

Согласен что async/await удобен, но в этой ситуации обычно после запроса еще что-то надо сделать(например маску загрузки отобразить, может еще какие-то данные подтянуть и тп), а значит придется использовать then/catchError, что не особо отличается от калбэков. К тому же минус catchError, что он еще и ловит ошибки в then, когда калбэки этого минуса не имеют.
Также у async/await нет способа обработать ошибки кроме как try/catch, что все же лучше оставлять для каких-то кардинальных ошибок(например null там, где не должен быть или ошибка парсинга), да и догадаться до этого сложно, так как в либе нигде такого поведения нет.

> Насчёт поиска. Сейчас там нет калбека для ошибки и в случае ошибки просто сбрасывается сессия. Т.е. пользователь будет бесконечно ждать результата и не узнает об ошибке. Это стоит поправить

Что-то не вижу о чем ты говоришь, там же есть `onSuggestListenerError`? Может мы о разном говорим?

2021-07-26 20:11 UTC, ILAgent commented
>Что-то не вижу о чем ты говоришь, там же есть onSuggestListenerError? Может мы о разном говорим?
Я вот про что
```
static Future<CancelSuggestCallback> getSuggestions({
    required String address,
    required Point southWestPoint,
    required Point northEastPoint,
    required SuggestType suggestType,
    required bool suggestWords,
    required SuggestSessionCallback onSuggest
  }) 
```
Тут нет возможности обработать ошибку. Если мапкит кинет onError, произойдёт вот это
```
static void _onSuggestListenerError(dynamic arguments) {
    _cancelSuggestSession(arguments['listenerId']);
  }
```
Сессия отменится, а клиент продолжит ждать непонятно чего.

2021-07-26 20:27 UTC, ILAgent commented
>Согласен что async/await удобен, но в этой ситуации обычно после запроса еще что-то надо сделать(например маску загрузки отобразить, может еще какие-то данные подтянуть и тп), а значит придется использовать then/catchError, что не особо отличается от калбэков.

Есть много способов работы с Future. Это очень гибкий, а главное - стандартный инструмент для Dart. Их можно комбинировать, преобразовывать в стримы и т.д. Твоё апи выбивается из всего этого. Даже использовать Future.then - лучше изобретения своих калбеков, т.к. стандартно.

По поводу ошибок. Я уже говорил, что согласен - не надо превращать ошибки мапкита в дартовые эксепшены. Их можно возвращать в поле результата. Посмотри плз мой пример из соседнего пр, поле `String? error;`  https://github.com/Unact/yandex_mapkit/pull/119#discussion_r676905001

2021-07-27 10:22 UTC, DCrow commented
> Тут нет возможности обработать ошибку. Если мапкит кинет onError, произойдёт вот это

Действительно, не заметил. Надо бы поправить.

> Есть много способов работы с Future. Это очень гибкий, а главное - стандартный инструмент для Dart. Их можно комбинировать, преобразовывать в стримы и т.д. Твоё апи выбивается из всего этого. Даже использовать Future.then - лучше изобретения своих калбеков, т.к. стандартно.

Я не пытаюсь с этим спорить, я пытаюсь добиться, чтобы имплементация была ясной и понятной для пользователей этой либы. В данном случае две проблемы было это ошибки и что отличается от Suggest/Search(в соседнем PR).
Вариант, который сейчас есть обе проблемы не решает. И если отличие можно поправить, то проблему с ошибками не получается решить в текущем варианте.

Твой вариант в https://github.com/Unact/yandex_mapkit/pull/119#discussion_r676905001 нравится, если в таком варианте сделать и тут, то у меня нет возражений(если конечно в во всех трех вариантах Suggest/Search/Routing будет одна имплементация). Пусть юзера сами решают как им работать с сессией.

2021-07-27 20:06 UTC, ILAgent commented on lib/src/types/driving/request_point.dart
> +enum RequestPointType { wayPoint, viaPoint }
А зачем? Это же очень неудобно?

2021-07-27 20:11 UTC, ILAgent commented on example/lib/examples/router_page.dart
> +                            await _controller?.removePolyline(_route!);
>late для этого случая не подходит, так как во время построения widget во flutter, _controller вполне может быть null, а вот в действиях кнопок мы уверены, что он не null.

Мы знаем, что когда начинаем его использовать, он уже инициализирован. Для этих случаев late и сделан.

2021-07-28 12:21 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexDrivingRouterHandlerImpl.java
> +                new DrivingRouteListener() {
Класс бы все равно хорошо бы вынести как отдельный приватный, внутри этого класса.
Поддерживать проблемно, особенно когда внутри другого метода

2021-07-28 12:23 UTC, DCrow commented on example/lib/examples/router_page.dart
> +                            await _controller?.removePolyline(_route!);
Мы может и знаем, но в примере не видно, что в том же initState контроллер еще null. 
На мой взгляд late только больше будет путать, что _controller, где-то ранее инициализируется.

2021-07-28 12:26 UTC, DCrow commented on lib/src/types/driving/request_point.dart
> +enum RequestPointType { wayPoint, viaPoint }
Смотря как посмотреть, искать например проще если в отдельном файле. 
Дорабатывать, соглашусь, менее удобно.

2021-07-28 16:22 UTC, cream-cheeze commented on ios/Classes/YandexDrivingRouter.swift
> +    private var session: YMKDrivingSession?
session здесь не лишнее? Ниже массив сессий, и вроде бы нигде не используется.

2021-07-28 19:56 UTC, ILAgent commented on example/lib/examples/router_page.dart
> +                            await _controller?.removePolyline(_route!);
> На мой взгляд late только больше будет путать, что _controller, где-то ранее инициализируется.

 Почему путать. late означает, что значение не может быть null и что оно инициализируется до первого использования. Как раз наш случай.

2021-07-28 20:03 UTC, ILAgent commented on lib/src/types/driving/request_point.dart
> +enum RequestPointType { wayPoint, viaPoint }
Это по сути одна составная сущность, предлагаю не раскидывать её по разным файлам.

2021-07-29 08:13 UTC, DCrow commented on lib/src/types/driving/request_point.dart
> +enum RequestPointType { wayPoint, viaPoint }
Ок, тогда другие сущности тоже было бы хорошо также прибрать.

2021-07-29 08:21 UTC, DCrow commented on example/lib/examples/router_page.dart
> +                            await _controller?.removePolyline(_route!);
Ладно пусть будет late. Потом остальные примеры тоже поменяю. 

PS Просто боюсь потом будут приходить с вопросами в Issue... Из-за того что в initState или еще где-нить ранее значение null.

2021-08-01 20:06 UTC, ILAgent commented
Переделал suggest на future. Можно смореть.

2021-08-01 20:07 UTC, ILAgent commented on lib/src/types/driving/request_point.dart
> +enum RequestPointType { wayPoint, viaPoint }
suggest сделал по аналогии, остальное трогать излишне имхо в этом пр

2021-08-07 16:10 UTC, cream-cheeze commented on lib/src/yandex_driving_router.dart
> +    return DrivingSession(futureRoutes, () => _cancelSession(sessionId));
Изучаю твой пример, чтобы привести поиск к единству, в формате, который вы предложили с @DCrow.

И всё же, мне кажется, что не совсем корректно здесь получается – ты не возвращаешь из нативного кода результат (не комплитишь Future вызовом result(resultRoutes)) до тех пор, пока не отработает routeHandler – т.е. код dart не получает сигнала о фактическом создании сессии. При этом, ты сразу же создаёшь в dart объект сессии, и в этот момент на стороне ios/android сессии ещё нет. Может получиться, что на стороне dart ты пытаешься отменить сессию, а ничего не происходит, потому что сессия фактически ещё не поднята...

Более правильный подход, как мне кажется, – чтобы методы requestRoutes или searchByText, как в моём случае, отвечали dart'у не по факту отработки респонс-хэндлера, а по факту создания сессии. В таком случае твой вариант с одновременным возвращением сессии и результата не будет работать, и здесь понадобятся либо колбэки, либо стрим.

2021-08-07 16:16 UTC, cream-cheeze commented on lib/src/yandex_driving_router.dart
> +    return DrivingSession(futureRoutes, () => _cancelSession(sessionId));
Убедиться в этом можно расставив принты в дарте и в свифте, например.
Вот, что получается (с расшифровкой):

- 2021-08-07 18:57:43.533528+0300 Runner[41161:19352193] flutter: will _buildRoutes - до вызова await _buildRoutes() в dart
- 2021-08-07 18:57:43.535782+0300 Runner[41161:19352193] flutter: requestRoutes
- requestRoutes method called - вызван handle для requestRoutes в swift
- 2021-08-07 18:57:43.549663+0300 Runner[41161:19352193] flutter: session got - dart получил объект сессии
- session created - в swift после отработки requestRoutes

Т.е. сессия в dart появилась раньше, чем настоящая сессия mapkit.

2021-08-08 13:37 UTC, ILAgent commented
> Может получиться, что на стороне dart ты пытаешься отменить сессию, а ничего не происходит, потому что сессия фактически ещё не поднята...

Кажется это невозможно, т.к. отмена тоже  - тоже  future, соответственно будет в очереди позже.

2021-08-08 16:08 UTC, cream-cheeze commented
> > Может получиться, что на стороне dart ты пытаешься отменить сессию, а ничего не происходит, потому что сессия фактически ещё не поднята...
> 
> 
> 
> Кажется это невозможно, т.к. отмена тоже  - тоже  future, соответственно будет в очереди позже.

Наверное, да, это будет нормально работать - я проверил мгновенную отмену - вроде отрабатывает как надо. Но не могу с уверенностью сказать, что не возникнет каких-либо сайд-эффектов.

2021-08-08 16:19 UTC, ILAgent commented
> > > Может получиться, что на стороне dart ты пытаешься отменить сессию, а ничего не происходит, потому что сессия фактически ещё не поднята...
> > 
> > 
> > Кажется это невозможно, т.к. отмена тоже  - тоже  future, соответственно будет в очереди позже.
> 
> Наверное, да, это будет нормально работать - я проверил мгновенную отмену - вроде отрабатывает как надо. Но не могу с уверенностью сказать, что не возникнет каких-либо сайд-эффектов.

Сессия кроме отмены ничего не умеет, поэтому думаю можно быть уверенным)

2021-08-09 11:56 UTC, cream-cheeze commented on ios/Classes/YandexDrivingRouter.swift
> +            self.sessions.removeValue(forKey: sessionId)
Кстати, я смотрю, ты тут сразу же после получения ответа удаляешь сессию, хотя нативная версия mapkit предусматривает метод retry, который позволяет повторить попытку создания сессии в случае ошибки.

2021-08-09 12:06 UTC, ILAgent commented on ios/Classes/YandexDrivingRouter.swift
> +            self.sessions.removeValue(forKey: sessionId)
Да, не поддержал retry. Не велика потеря, можно новую сессию создать.

2021-08-17 12:00 UTC, ILAgent commented
@DCrow ну что, примёржим?

2021-08-17 14:43 UTC, merged

2021-08-17 14:43 UTC, DCrow commented
Давай

2021-09-23 09:39 UTC, k0lourful commented
Возможно добавить типы маршрута? Хотя бы пешеходный