#102 Поддержка прямого геокодирования (поиска адреса по строке)
Unact/yandex_mapkit pull request #119
Opened 2021-07-12 12:28 UTC by cream-cheeze

Реализован один из видов поиска – [поиск по тексту (submit)](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/search/SearchManager.html#_4). 
На текущий момент поддержано два типа поиска: geo и biz, и два типа геометрии: point и boundingBox. Поддержка biz пока что ограниченная - возвращается только базовый набор полей, описывающих объекты бизнес-инфраструктуры (полей доступно намного больше). 
Не реализованы возможности ресабмита и уточнения запроса, а также получения следующей страницы результатов. Из работы с сессией реализован только метод отмены - [cancel](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/search/Session.html#_5). В принципе, насколько я смог оценить, этот функционал в большинстве случаев и не понадобится.

Следом, если с этим PR всё ок, реализую обратный геокодинг (адрес по точке), т.к. он мне тоже нужен в проекте.

2021-07-21 20:19 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Не предусмотрена возможность запуска нескольких сессий параллельно

2021-07-21 20:44 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Да, не стал пока усложнять. Откровенно говоря, доработки делаю под свои задачи, и пока не вижу кейсов, когда могло бы понадобиться содержать параллельно несколько сессий. В примере от Яндекса, на который опирался, работа также ведется с единственной сессией. Но, возможно доработать в будущем - пока лучше так, чем ничего.

2021-07-23 09:01 UTC, DCrow requested changes
Спасибо за проделанную работу!

Оставил комменты. 
Хорошая фича получается. 
Также много хороших новых сущностей увидел, которые хорошо бы, и в других местах тоже начать использовать.

2021-07-23 09:01 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    List<Number>        snippetsOption              = (List<Number>) options.get("snippets");
Этот же параметр всегда пустой массив. 
Лучше либо сразу имплементировать, либо убрать. 

Не используемый код = не рабочий код = закомментированный код

2021-07-23 09:06 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Тут соглашусь с @ILAgent, надо бы поддерживать такое. 
Мне кажется, что в одной сессии могут быть подводные камни типо кривого кеширования, либо протухания сессии, которые пользователь(разработчик приложения) либы не сможет разрешить, кроме как перезапуском всего приложения(но такое же нельзя говорить обычным пользователям)

Да и вроде не сложная доработка?

2021-07-23 10:04 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Ок, подумаю над этим.

2021-07-23 10:15 UTC, cream-cheeze commented on lib/src/types/search_type.dart
> +  // transit,
Специально оставил - подумал, что так будет проще ориентироваться тем, кто будет будет пытаться найти остальные типы, или захочет дополнить функционал. Могу убрать, конечно, если это чему-то сильно противоречит. Точно убрать?

2021-07-23 10:16 UTC, cream-cheeze commented on lib/src/types/search_type.dart
> +  // transit,
Кстати, когда делал, заметил одну потенциальную проблему, которая в будущем может проявиться - в getSuggestions подобный enum используется не совсем правильно - при вызове нативного кода параметр передаётся как suggestType.index, что в принципе соответствует текущему enum, в iOS например:

typedef NS_OPTIONS(NSUInteger, YMKSuggestType) {
    /**
     * Default value: server-defined types are returned.
     */
    YMKSuggestTypeUnspecified = 0,
    /**
     * Toponyms.
     */
    YMKSuggestTypeGeo = 1,
    /**
     * Companies.
     */
    YMKSuggestTypeBiz = 1 << 1,
    /**
     * Mass transit routes.
     */
    YMKSuggestTypeTransit = 1 << 2
};

но если добавится ещё один элемент, то index уже не прокатит.

В этой ветке не стал ничего делать, но пометку себе оставил.

2021-07-23 10:28 UTC, cream-cheeze commented on lib/src/types/search_type.dart
> +extension SearchTypeExtension on SearchType {
Да, это я ошибся - делал специально, а вместо searchOptions.searchType.value передаю searchOptions.searchType.index - поправлю. 

Сделано потому, что в mapkit этот параметр не соответствует просто индексу enum – там маска используется. Экстеншн позволяет задать value, соответствующее каждому элементу enum. Можно накладывать сразу несколько масок и получать комбинированный поиск - например, по geo и biz одновременно.

Далее, в iOS, например, из этого значение оборачивается в [YMKSearchType](https://yandex.ru/dev/maps/archive/doc/mapkit/3.0/concepts/ios/mapkit/ref/YMKSearchOptions.html#property_detail__property_searchTypes).

2021-07-23 10:36 UTC, cream-cheeze commented on lib/src/types/search_snippet.dart
> +enum SearchSnippet {
Со сниппетами там отдельная песня - их очень много, и это нужно всё обрабатывать и тестировать - я в итоге пока отказался от их имплементации, но enum уже запилил. Не удалять же - в будущем пригодится. Пока я в методе flutter не стал добавлять параметр snippets, а в нативный код передаю просто пустой массив.

2021-07-23 10:41 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +class SearchResponse extends Equatable {
Сделал, чтобы облегчить основной код от преобразований json. Возможно, ещё и при обратном поиске пригодится, если там структура такая же..

Я бы, кстати, вообще предложил в контроллере вместо всех этих методов: _polygonParams, _circleParams и т.п. использовать методы toJson внутри типов - это облегчит контроллер. Сделал так для плейсмарков в другой ветке.

2021-07-23 10:43 UTC, cream-cheeze commented on lib/src/types/search_item_business_metadata.dart
> +    if (shortName != null) {
Ок

2021-07-23 10:45 UTC, cream-cheeze commented on lib/src/types/bounding_box.dart
> +class BoundingBox {
Да, я себя ограничивал, чтобы влезать по-минимуму в код, не касающийся конкретного функционала, ну и время тоже ограничено. Лучше это отдельным PR после.

2021-07-23 10:55 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +      onSearchError(NSError(domain: "", code: 0, userInfo: ["message" : "Invalid geometry"]))
Ну это скорее как подстраховка - по крайней мере сейчас dart не пропускает такого кейса, ну и чтобы if-else покрывал все кейсы и разработчик был спокоен вне зависимости от того, проверяется ли это на стороне дарта или нет. 
Можно и убрать, если настаиваешь.

2021-07-23 10:56 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    case "cancelSearchSession":
Речь про cancel? По ходу я его профукал..

2021-07-23 10:57 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    String  originOption                    = (String) options.get("origin");
Да, забыл похоже. Какие-то второстепенные параметры. Добавлю для порядка.

2021-07-23 12:04 UTC, DCrow commented on lib/src/types/search_type.dart
> +  // transit,
Да, действительно бага получается. 

Другие типы все же лучше убрать. 
Кажется что они только путать будут, да и пока оно закомменчено, оно все равно никак не используется и может так долго висеть без всяких доработок. 
Лучше тогда оставить коммент, почему не все типы указаны, а только набор

2021-07-23 12:05 UTC, DCrow commented on ios/Classes/YandexSearch.swift
> +    case "cancelSearchSession":
Да, про него. Надо бы добавить

2021-07-23 12:28 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +}
Не понял про последнюю строку.. Перед закрывающей скобкой класса чтоли?

2021-07-23 12:36 UTC, DCrow commented on lib/src/yandex_search.dart
> +}
После нее. Я об [этом](https://thoughtbot.com/blog/no-newline-at-end-of-file#:~:text=So%2C%20it%20turns%20out%20that,is%20a%20line%20%E2%80%9Cterminator%E2%80%9D.)

2021-07-23 12:40 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +}
Ясно, не в курсе был, добавлю

2021-07-23 12:48 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +class SearchResponse extends Equatable {
А, ну и вспомнил ещё, что побудило - смотрел на SuggestSessionCallback, когда делал, его сигнатура выглядит так: 

typedef SuggestSessionCallback = void Function(List<SuggestItem> msg);

В моём случае объект более сложный - помимо items содержит ещё атрибут found, и может в последствии добавиться ещё что-то. Поэтому и запилил отдельный тип, чтобы можно было его передать в колбек.

2021-07-23 13:11 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +        switch kind {
Да вообще то совпадают - я в дарте отзеркалил этот enum. Просто решил подстраховаться на случай, если вдруг Яндекс у себя порядок поменяет у этого enum'а, чтобы на нас это не повлияло никак. Не могу предположить зачем, но теоретически они могут это сделать, и будут думать, что это безопасно, потому что в нативном коде ты скорее всего работаешь с самим enum'ом, а не его rawValue. Велика вероятность такое не заметить при обновлении mapkit.

2021-07-23 13:16 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +        switch kind {
А в отдельный метод не вижу особого смысла выделять, так как это и есть уже отдельный метод, который выдирает компоненты из адреса. Да им метод getAddressComponents вполне простой сам по себе.

2021-07-23 14:27 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +      throw('geometry is invalid: point or boundingBox required');
Готово

2021-07-23 14:28 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +    if (geometry.point != null) {
Готово - сделал toJson внутри Geometry.

2021-07-23 14:28 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +}
Готово

2021-07-23 14:28 UTC, cream-cheeze commented on lib/src/types/search_type.dart
> +  // transit,
Убрал

2021-07-23 14:29 UTC, cream-cheeze commented on lib/src/types/search_item_business_metadata.dart
> +    if (shortName != null) {
Готово

2021-07-23 14:29 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +      onSearchError(NSError(domain: "", code: 0, userInfo: ["message" : "Invalid geometry"]))
Убрал

2021-07-23 14:30 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +      let geometryBoundingBox = geometry["boundingBox"] as? [String:Any],
Готово

2021-07-23 14:30 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    case "cancelSearchSession":
Это вместе с мулти-сессиями сделаю

2021-07-23 14:31 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +          switch (addressComponentKind) {
Ответил выше.

2021-07-23 14:31 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +      yaListener.onSearchError(new SearchError("Invalid geometry"));
Готово

2021-07-23 14:31 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    String  originOption                    = (String) options.get("origin");
Готово

2021-07-23 14:31 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    List<Number>        snippetsOption              = (List<Number>) options.get("snippets");
Готово

2021-07-23 15:18 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Смотрите, метод submit, который осуществляет поиск, всегда возвращает новую сессию, которая необходима только для перезапросов или отмены запроса. Кэширование, протухание и т.п. - это здесь не при чём - поиск не просит передавать sessionId, соответственно ситуация, в которой мы хотим что-то найти, а сессия протухла, не существует.

В текущей реализации у нас есть ссылка на последнюю сессию, с помощью которой, как раз, и можно выполнять перезапросы, либо вызвать cancel. Как только мы снова вызываем submit (searchByText во flutter), например, когда ищем новый адрес, сессия перезаписывается.

Так вот вопрос, зачем нам собирать ссылки на все предыдущие сессии, коих в рамках одной пользовательской сессии приложения может создаться великое множество? Они будут просто копиться никому не нужные и отжирать память.

2021-07-23 16:08 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    case "cancelSearchSession":
Готово

2021-07-23 16:09 UTC, cream-cheeze commented
Всё доделал, кроме нескольких моментов, которые пока остаются открыты, включая сохранение нескольких сессий.

2021-07-23 20:34 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
У тебя тут сейчас утечка. Если я дёрну два раза submit, будет создано две сессии, но ссылка на первую будет потеряна - её не отменить. И она либо будет висеть произвольно долго, либо стрельнёт значением в произвольный момент.

>Так вот вопрос, зачем нам собирать ссылки на все предыдущие сессии, коих в рамках одной пользовательской сессии приложения может создаться великое множество? 

Если я дёрнул searchByText 5 раз одновременно, то я хочу получить 5 ответов - на каждый запрос. Логично же)

Более дешёвое решение - запретить создание нескольких сессий одновременно. Т.е. при вызове searchByText отменять предыдущую, если она есть. Или падать, чтобы было явно. Так не будет утечки, по крайней мере. Но лучше сделать нормально.

2021-07-24 14:22 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Метод cancel, если ты про него, отменяет не сессию, а поисковый запрос, при этом сессия продолжает жить. Метода уничтожения сессии я там не видел. Как только ссылка на сессию пропадает, сессия уничтожается, насколько я понял.

Единственное, в чём ты прав - если подряд дёрнуть searchByText, то результат ты получишь только по последней, так как предыдущие отменятся. Вот только, насколько это реальный кейс? Это же мобильное приложение, а не бэкэнд какой-то, который параллельно парсит адреса пачками. По-моему, это ненужное усложнение, реального применения не вижу.

Допустим, я бы сделал сохранение каждой сессии, которая создаётся при каждом вызове searchByText... Какой в этом случае ты видишь алгоритм работы с поиском на стороне flutter - вызвал searcByText, обработал результат, потом явно удалил сессию (под удалением понимаю удаление ссылки, а не метод cancel)? Сложновато получается. Как раз в этом случае люди могут забывать убивать и будут утечки.

2021-07-25 09:31 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
>Метод cancel, если ты про него, отменяет не сессию, а поисковый запрос

Я про это и говорю. Сам объект соберётся сборщиком,конечно.

>Единственное, в чём ты прав - если подряд дёрнуть searchByText, то результат ты получишь только по последней, так как предыдущие отменятся. 

Нет, в твоей реализации предыдущие не отменятся, и результат ты можешь получить от всех, а не от последней. В этом и беда.

>Это же мобильное приложение

Плохой интернет, пользователь несколько раз жмёт на кнопку...

>вызвал searcByText, обработал результат, потом явно удалил сессию 

Нет, сессия так же завершается при получении ответа или оишиби. В этом случае её надо удалять из коллекции. В саджесте сейчас этого, кстати, нет - надо поправить.

2021-07-25 09:51 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Так где сейчас утечка?

Почитай [эту статью](https://habr.com/ru/company/yandex/blog/428564/).

> Сразу после вызова submit управление вернётся к вашему коду, а когда MapKit получит ответ от сервера, то будет вызван SearchListener.
> 
> Поисковая сессия позволяет:
> 
> Отменить запрос. Например, если пользователь закрывает экран поиска.
> Повторить запрос в случае ошибки. Например, если были какие-то проблемы с сетью.
> Продолжить взаимодействие с поиском после полученного ответа. Перезапросы делаются именно через сессию.
> 
> **_---------> Сессия при уничтожении автоматически отменяется. Это значит, что если её не сохранить на стороне клиентского кода, то поиск работать не будет. <-----------_**
>
> Не забывайте сохранять сессию, сессия – ваш друг!

Из этого следует, что если я отправляю запрос и следом за ним отправляю новый, перезаписывая первую сессию, то первая сессия отменяется автоматически, и результат я не получу.

> Плохой интернет, пользователь несколько раз жмёт на кнопку...

Такие ситуации разгуливаются на стороне UI - рисуй прелоадер, блокируй нажатие кнопки, пока не вернулся ответ.... Если этого не делаешь, то по логике получишь только последний ответ.

> Нет, сессия так же завершается при получении ответа или ошибки. В этом случае её надо удалять из коллекции. В саджесте сейчас этого, кстати, нет - надо поправить.

Во-первых, выходит, это излишне, так как сессия автоматически отменится при новом запросе (см. статью выше). А во-вторых, как при таком подходе ты сможешь использовать сессию для уточняющих запросов или получения следующей страницы, если сразу после получения первого ответа, ты её убьёшь?

2021-07-25 10:48 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
>Сессия при уничтожении автоматически отменяется. Это значит, что если её не сохранить на стороне клиентского кода, то поиск работать не будет.

Это не так работает. При потере ссылки на сессию её соберёт сборщик вместе с лиснером - ответа после этого  мы не получим. Но когда соберёт - мы не знаем, тут неопределённость, а значит - дырка. Т.е. ответ может прийти до сборки.
В статье акцент на том, что если мы хотим точно дождаться ответа - ссылку надо держать.

>Такие ситуации разгуливаются на стороне UI

Разрулить можно что угодно, это не повод делать дырявое api.

>А во-вторых, как при таком подходе ты сможешь использовать сессию для уточняющих запросов или получения следующей страницы, если сразу после получения первого ответа, ты её убьёшь?

Хороший поинт. В таком случае вижу два варианта: 1 -да,  закрывать явно; 2 - остановиться на дешёвом решении
> при вызове searchByText отменять предыдущую, если она есть. Или падать, чтобы было явно.

2021-07-25 17:07 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Уточни, пожалуйста, ты как конкретно предлагаешь закрывать сессию?

2021-07-25 18:19 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Так, давай по-порядку...

С чего вообще начался этот разговор? Ты сказал, что не предусмотрена возможность запуска нескольких сессий параллельно. Так вот, повторюсь, я считаю, что такой функционал в реальности вряд ли кому-то потребуется. Если разработчик позволяет нажимать на условную кнопку поиска 5 раз подряд, то это его решение - никакой проблемы здесь нет – первые 4 сессии будут уничтожены, последняя 5-я жива и по ней вернётся результат. Умозаключение про дырявое api здесь не совсем уместно.

Проведи эксперимент – измени фрагмент кода в примере на этот, и посмотри что будет:

```
onPressed: () {
  search('Тверская 1');
  search('Тверская 2');
  search('Тверская 3');
  search('Тверская 4');
  search('Тверская 5');
  search('Тверская 6');
  search('Тверская 7');
  search('Тверская 8');
  search('Тверская 9');
  search('Тверская 22');
},
title: 'Query'
```

Спойлер: получишь результат только по последнему адресу – что и ожидается, такое поведение вполне логично.

Далее ты пишешь:

> У тебя тут сейчас утечка. Если я дёрну два раза submit, будет создано две сессии, но ссылка на первую будет потеряна - её не отменить. И она либо будет висеть произвольно долго, либо стрельнёт значением в произвольный момент.

Никакой утечки здесь нет – **потерянная ссылка это и есть единственный метод удаления поисковой сессии**, никаких специальных средств для этого не предусмотрено. Позже ты сам предлагаешь "удалять из её коллекции" – по-сути, то же самое, что и происходит сейчас, но без коллекции (которая и не нужна). Удалять последнюю открытую сессию необходимости нет – она, как уже говорил, может быть повторно использована для последующих запросов.

Мою позицию косвенно подтверждает статья, на которую я ссылаюсь, и [официальный пример использования mapkit](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/SearchViewController.swift), в котором сессия используется именно так, как я и реализовал – сохраняется последняя сессия, с ней и идёт работа.

2021-07-25 20:30 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
>Спойлер: получишь результат только по последнему адресу – что и ожидается, такое поведение вполне логично.

Это поведение не гарантируется мапкитом. То, что в твоём примере сборщик быстро собирает сессии, не означает, что так будет у всех.  Это касается Андроида в первую очередь. В свифте нет сборщика, там подсчёт сылок. Возможно, поэтому поведение более детерминированно.

>потерянная ссылка это и есть единственный метод удаления поисковой сессии

Если сессия не нужна до её завершения - нужно дёрнуть метод отмены. Он не просто так существует.

2021-07-26 07:26 UTC, DCrow commented on lib/src/types/search_options.dart
> +    if (resultPageSize != null) {
А зачем мы это тут проверяем? Надо же только на стороне Swift/Java проверять это(к тому же там, тоже идет проверка на null)

2021-07-26 07:31 UTC, DCrow commented on example/lib/examples/search_page.dart
> +    // YandexSearch.cancelSearch();
Лучше бы это вызывать тогда когда мы уходим со страницы в `dispose`. Так более реалистичный вариант использования получается.

И что будет, если вызовем `cancelSearch`, когда еще ни разу не вызывали `searchByText`? 
Или если несколько раз подряд вызовем `cancelSearch`?

2021-07-26 07:32 UTC, DCrow commented on lib/src/yandex_search.dart
> +    await _channel.invokeMethod<void>('cancelSearch', null);
Тут же параметр не нужен?

2021-07-26 07:58 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
>Спойлер: получишь результат только по последнему адресу – что и ожидается, такое поведение вполне логично.

Спойлер не сработал, получил результаты по всем запросам. (Как раз на симуляторе андроида)

Опять же, тут @ILAgent прав, так как GC не обязательно сразу срабатывает, listener, сам объект сессии, может быть какое-то время не быть собран и спокойно жить, и возвращать результаты в listener, который в свою очередь все отправит в dart. Мы же ожидаем, что такого не будет.

>  А во-вторых, как при таком подходе ты сможешь использовать сессию для уточняющих запросов или получения следующей страницы, если сразу после получения первого ответа, ты её убьёшь?

Я бы на данный момент такой вариант не рассматривал, особенно с учетом того, что в дарте мы всегда отправляем все параметры, и нет возможности уточнений вводить. К тому же тогда явно надо по-другому работу в дарте делать, также создавать отдельным методом сессию, и с ней работать(отправлять запрос, retry, уточнение и тп)

> Мою позицию косвенно подтверждает статья, на которую я ссылаюсь, и официальный пример использования mapkit, в котором сессия используется именно так, как я и реализовал – сохраняется последняя сессия, с ней и идёт работа.

Это не отменяет того, что команда Яндекс сделала возможность иметь более 1 сессии. Если бы действительно хотели бы чтобы использовалась одна сессия, то могли бы сделать один синглетон(как это с SearchFactory и тп сделано).

2021-07-26 09:03 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Если сессия не нужна до её завершения - нужно дёрнуть метод отмены. Он не просто так существует.

Да нет никакого метода, ребята! ) Метод **cancel** отменяет поисковый запрос, он не сессию. Нет никакого другого способа, кроме как удалить все ссылки на сессию в клиентском коде. Ровно это сейчас и происходит при последовательном вызове searchByText несколько раз подряд. Если добавлять сессии в коллекцию, а потом удалять оттуда, то ничего принципиально не изменится.

2021-07-26 09:07 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Спойлер не сработал, получил результаты по всем запросам. (Как раз на симуляторе андроида)
> 
> Опять же, тут @ILAgent прав, так как GC не обязательно сразу срабатывает, listener, сам объект сессии, может быть какое-то время не быть собран и спокойно жить, и возвращать результаты в listener, который в свою очередь все отправит в dart. Мы же ожидаем, что такого не будет.

Ок, я проверял на iOS, соглашусь, что был не прав по данному примеру. Но, как написал только что выше, коллекция ничего не изменит. Ты точно так же, как я сейчас перезаписываю ссылку, удалишь объект из коллекции, и точно так же останется неизвестно, когда его там java подберёт. Можно просто перед каждым новым вызовом submit отменять предыдущий запрос (не сессию!) с помощью метода cancel() - тогда точно не получишь результат от предыдущих вызовов.

2021-07-26 09:10 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Я бы на данный момент такой вариант не рассматривал, особенно с учетом того, что в дарте мы всегда отправляем все параметры, и нет возможности уточнений вводить. К тому же тогда явно надо по-другому работу в дарте делать, также создавать отдельным методом сессию, и с ней работать(отправлять запрос, retry, уточнение и тп)

Не совсем так - сессия, например, позволяет запросить следующую страницу результатов, если она есть, так что очевидные кейсы использования есть.

И не понял - как это создавать сессию отдельным методом? Сессия создаётся при каждом поиске, её нельзя передать в submit.

2021-07-26 10:06 UTC, cream-cheeze commented on example/lib/examples/search_page.dart
> +    // YandexSearch.cancelSearch();
Может и более реалистичный, но проверить будет практически невозможно - нужно иметь невероятную ловкость рук, чтобы уйти со страницы раньше, чем будет получен результат, а так наглядно (по принтам) видно, что запрос отменяется. Добавил dispose тоже - лишним не будет.

В iOS ничего не случится, а вот в андроиде был бажок - добавил проверку, что сессия != null перед отменой. Теперь безопасно вызывать сколько угодно раз.

2021-07-26 10:15 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +    await _channel.invokeMethod<void>('cancelSearch', null);
В текущей имплементации не нужен, т.к. нативный код хранит только одну ссылку на последнюю сессию, и ему ничего больше не требуется для отмены.

2021-07-26 10:21 UTC, cream-cheeze commented on lib/src/types/search_options.dart
> +    if (resultPageSize != null) {
Да, в принципе, ты прав - лишнее, убрал. 
Проверяю, чтобы не создавать лишний ключ в json, т.к. бывало по опыту, что вместо null передашь пустую строку или 0 и поле уже не null. Но в данном случае такого не случится.

2021-07-26 12:46 UTC, DCrow commented on lib/src/yandex_search.dart
> +    await _channel.invokeMethod<void>('cancelSearch', null);
Так убрать тогда же надо, если не нужен параметр

2021-07-26 12:46 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Да нет никакого метода, ребята! ) Метод cancel отменяет поисковый запрос, а не сессию. Нет никакого другого способа, кроме как удалить все ссылки на сессию в клиентском коде. Ровно это сейчас и происходит при последовательном вызове searchByText несколько раз подряд. Если добавлять сессии в коллекцию, а потом удалять оттуда, то ничего принципиально не изменится.

Да тут речь, не о том чтобы уничтожить сессию, как-то по особому, а то что нам вернутся результаты из предыдущей сессии, и если мы работает только с одной сессией, их не надо возвращать, поэтому и надо вызывать отмену, как говорит @ILAgent.

> Но, как написал только что выше, коллекция ничего не изменит.

Тут согласен, в этом плане коллекция не приносит пользы.

> Не совсем так - сессия, например, позволяет запросить следующую страницу результатов, если она есть, так что очевидные кейсы использования есть.

Вот ты тут сам дал кейсы, когда надо иметь ссылки на старые сессии. Я говорил именно про текущую доработку, так как ты в начале писал, что не реализовывал след. страницу результатов.

> И не понял - как это создавать сессию отдельным методом? Сессия создаётся при каждом поиске, её нельзя передать в submit.

Я тут больше что в дарт будет метод, который создает сессию(которая и на native стороне тоже создается), и уже в `searchByText` передается она. Это о том, как оно в будущем может выглядеть.


Мне кажется сейчас есть два варианта как можно поправить
1. Сделать все же поддержку нескольких сессий(что как раз даст возможность, в будущем безболезненно доработать поддержку перехода на след страницу результатов)
2. Сделать одну сессию, с которой юзер всегда работает.

Вариант с одной сессией меньше нравится, потому что потом все равно придется переделывать, чтобы поддерживать пагинацию и всякие ретраи. Да и получается что `getSuggestions` в этом же классе частично по другому работает(его тогда надо привести в тот же формат, что и `searchByText`)

2021-07-26 12:58 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Да тут речь, не о том чтобы уничтожить сессию, как-то по особому, а то что нам вернутся результаты из предыдущей сессии, и если мы работает только с одной сессией, их не надо возвращать, поэтому и надо вызывать отмену, как говорит @ILAgent.

Выше предложил, как это решить - вызывать cancel() перед submit() – это отменит предыдущий поиск, если он в процессе, и тогда предыдущий результат не будет возвращён.

> Вот ты тут сам дал кейсы, когда надо иметь ссылки на старые сессии. Я говорил именно про текущую доработку, так как ты в начале писал, что не реализовывал след. страницу результатов.

Это работает и с одной сессией. Просто в моём понимании нафиг никому не нужно одновременно работать с несколькими сессиями - главное, чтобы не было проблем в коде. Получение следующей страницы я действительно не реализовал, но в текущей реализации никто не мешает это сделать без доработок архитектуры - просто добавить метод типа getNextPage, который будет обращаться к последней активной сессии. Просто не хочу сейчас время на это тратить - кейс довольно специфический, на мой взгляд, в большинстве случаев одной страницы достаточно.

> Я тут больше что в дарт будет метод, который создает сессию(которая и на native стороне тоже создается), и уже в searchByText передается она. Это о том, как оно в будущем может выглядеть.

Создать сессию просто так не получится - можно создать только выполнив поисковый запрос с помощью вызова submit(). Не будешь же ты делать фиктивный поисковый запрос, чтобы создать сессию? Причём с этой сессией ты не сможешь начать новый поиск - только уточнение запроса или получение следующей страницы возможно с уже созданной сессией.

> Сделать все же поддержку нескольких сессий(что как раз даст возможность, в будущем безболезненно доработать поддержку перехода на след страницу результатов)

Всё ещё не вижу никакой связи между несколькими сессиями и возможностью получения следующей страницы..

2021-07-26 13:06 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Да и получается что getSuggestions в этом же классе частично по другому работает(его тогда надо привести в тот же формат, что и searchByText)

getSuggestions тоже можно было бы упростить - там так же, на мой взгляд, не нужна мульти-сессионность, и я, честно говоря, был немного смущён, когда впервые решил этим воспользоваться - непонятно было, зачем эти сессии создаются, а потом, как в примере написано, через 3 секунды отменяются.

Правда садджесты немного иначе устроен в mapkit - я там не видел метода отмены запроса например.

2021-07-26 13:10 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +    await _channel.invokeMethod<void>('cancelSearch', null);
null чтоли? Убрал.

2021-07-26 15:20 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> просто добавить метод типа getNextPage, который будет обращаться к последней активной сессии

В таком случае, как раз нужно иметь отдельную сессию, так как юзер может спокойно нажать на "след. страница" и потом сразу поменяет тип поиска(например с SearchType.geo, на SearchType.biz) и нам надо сразу сделать поиск с новым типом, а это вполне возможно может пересечься с переходом на "след. страницу", тогда не понятно что выполнится ранее.

Также же иногда бывают случаи, когда хочется что-то выполнить в фоновом режиме(без юзера), но и чтобы юзер тоже мог вводить и делать поиски в приложении отдельно от этого.

> Создать сессию просто так не получится - можно создать только выполнив поисковый запрос с помощью вызова submit()

Извиняюсь, действительно плохо посмотрел. В таком случае после вызова `searchByText` будет отдаваться сессия(какой-нить отдельный класс в дарте), которая уже позволит и другие страницы получать, и ретраи, и отмену ее.

> Всё ещё не вижу никакой связи между несколькими сессиями и возможностью получения следующей страницы..

Смысл тут в том, что если вызывать получение новой страницы и вместе с этим начинать новый поиск, то поведение получения новой страницы не детерминировано(edgecase, когда юзер почти одновременно вызывает эти методы). Она может как получить у старой сессии, так и у новой в зависимости от того как scheduler в dart запустит эти асинхронные методы.

2021-07-26 15:43 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> В таком случае, как раз нужно иметь отдельную сессию, так как юзер может спокойно нажать на "след. страница" и потом сразу поменяет тип поиска(например с SearchType.geo, на SearchType.biz) и нам надо сразу сделать поиск с новым типом, а это вполне возможно может пересечься с переходом на "след. страницу", тогда не понятно что выполнится ранее.
> 
> Также же иногда бывают случаи, когда хочется что-то выполнить в фоновом режиме(без юзера), но и чтобы юзер тоже мог вводить и делать поиски в приложении отдельно от этого.

Да не строятся так пользовательские интерфейсы. Если я что-то нашёл в гугле, нажал на вторую страницу, и не дождавшись ответа запустил новый поиск - значит я передумал получать вторую страницу, и хочу видеть результаты нового поиска.

> Смысл тут в том, что если вызывать получение новой страницы и вместе с этим начинать новый поиск, то поведение получения новой страницы не детерминировано(edgecase, когда юзер почти одновременно вызывает эти методы). Она может как получить у старой сессии, так и у новой в зависимости от того как scheduler в dart запустит эти асинхронные методы.

Всё то же решение, которое предлагал выше – вызывать cancel() перед каждым запросом. Если в процессе получения новой страницы пользователь начнёт новый поиск, то мы отменим получение новой страницы и вернём только результат нового поиска. Всё просто и понятно.

2021-07-26 15:54 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Единственное, с чем согласен из последнего поста - что не получится в моей реализации запустить параллельный с пользовательским поисковый процесс. Но это настолько узкий кейс, что даже сложно представить мобильное приложение, которое будет таким заниматься. И стоит ли ради очень редкого кейса усложнять api для всех остальных, и заморачивать их взаимодействием с параллельными сессиями, не нужными в 99% случаев. Давайте не забывать, что данный плагин в виду специфики флаттера не в состоянии повторить один-в-один сам мэпкит - мы здесь делаем некий абстрактный интерфейс для взаимодействия с картами, который вовсе не обязан (да и не в состоянии) быть копией нативной библиотеки.

2021-07-26 16:10 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
В общем, я больше не хочу спорить на этот счёт. Все аргументы я привёл - если не убедил, то мне проще переделать, как хотите, чтобы PR был смержен. Для моего приложения это всё равно не принципиально. Надо двигаться дальше уже... 

Только в таком случае, @DCrow, опиши, пожалуйста, как ты видишь доработку, чтобы не пришлось опять переделывать. Собственно, если мы решаем, что копим коллекцию всех поисковых сессий, и хотим, чтобы можно было запустить два поиска параллельно, то самостоятельно убивать предыдущие сессии не имеем права, как это где-то выше предлагалось. Получается, что ответственность за удаление сессии мы перекладываем на пользователя плагина? Т.е. если пользователь после завершения работы с сессией, не вызовет условный метод closeSession(sessionId), то сессия останется висеть в коллекции, и нас это устраивает. Всё так?

2021-07-26 16:15 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Для ясности, подытожу: если добавить в текущую реализацию вызов cancel() перед каждым новым submit(), то никаких логических или технических проблем не остаётся: ни утечек, ни неожиданных результатов и и.п. Получается, что мы просто  вернулись к самому первому вопросу, а именно: нужна ли в плагине возможность параллельного запуска нескольких поисков или нет?

2021-07-26 20:03 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Если что, поддержка нескольких сессий в моём представлении может выглядеть так. 

```
static Future<SearchSession> searchByText({
    required  String                searchText,
    required  Geometry              geometry,
    required  SearchOptions         searchOptions
})

class SearchSession {
  Future<SearchResponse> response;
  void Function() resubmit;
  
  void Function() dispose; 
}

class SearchResponse {
  int  found;
  List<SearchItem>?  items;
  String? error;
}
```

`dispose` надо вызывать обязательно, ничего не поделать. В дарте нет ни деструкторов, ни финализаторов ((

2021-07-27 10:32 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Получается, что ответственность за удаление сессии мы перекладываем на пользователя плагина?

Верно, точно так сейчас с Suggest работает.

> Получается, что мы просто вернулись к самому первому вопросу, а именно: нужна ли в плагине возможность параллельного запуска нескольких поисков или нет?

Да. Мне кажется есть в этом смысл, как минимум две другие часть Suggest и Routing(#118) поддерживают такое, было бы странно, если тут было по иному. 
Также, на мой взгляд, не просто так в нативной либе дана такая возможность. Вполне возможно есть какие-то кейсы, которые требуют работу с несколькими сессиями одновременно(например какой-нить сплит скрин, где пользователь хочет посмотреть данные по разным точкам бок о бок и потом как-нить уточнить их и тп). 

> Если что, поддержка нескольких сессий в моём представлении может выглядеть так.

Выглядит хорошо. Предлагаю в таком роде и делать поддержку сессий(надо не забыть и про Suggest). Тут вам с @ILAgent надо обсудить, чтобы прийти к одному решению для всех трех частей.

2021-07-27 10:40 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Не совсем понимаю, что ещё c @ ILAgent нужно обсуждать? Суть предложения относительно поиска я понял -  внесу изменения. Давайте только suggest в этой ветке не будем трогать, а то она бесконечной получается...

2021-07-27 11:17 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Если возражений на предложенное api нет, то саджест я поправлю в своём пр.

2021-07-27 11:33 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Визуально предложение нравится, но не совсем, мне кажется, это вписывается в текущую архитектуру... Не лучше ли будет в YandexSearch (dart) добавить методы: cancelSearch, retrySearch и т.п., которые на вход будут принимать сессию? В этом плагине так всё устроено, в том числе и контроллер - чтобы получить что угодно, мы дёргаем методы контроллера, хотя в действительности работаем с разными объектами мэпкита.

2021-07-27 12:23 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
> Если возражений на предложенное api нет, то саджест я поправлю в своём пр.

В целом нет, максимум что добавил бы, так это bool признак есть ошибка или нет. Что-то вроде такого
```dart
class SearchResponse {
  int found;
  List<SearchItem>? items;
  bool hasError;
  String? errorMsg;
}
```

> Визуально предложение нравится, но не совсем, мне кажется, это вписывается в текущую архитектуру...

Я больше вижу это следующим образом. Контроллер - это часть виджета YandexMap, и в целом он является его производным. То есть нам при рендере YandexMap отдается контроллер, который взаимодействует с картой, а мы в свою очередь с ним взаимодействуем. Для YandexSearch также получается, мы даем запрос(тут уже на поиск, вместо рендера) и получаем объект, который впоследствии работает с search/suggest и мы опять же работаем с ним.

2021-07-27 12:30 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Согласен с @DCrow , плюс сессия у нас - "богатая" сущность с состоянием и поведением, а не айдишник. Странно её так использовать.

2021-07-27 12:31 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
>В целом нет, максимум что добавил бы, так это bool признак есть ошибка или нет. 

По-моему это избыточно, достаточно проверить errorMsg на null

2021-07-27 12:43 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
Если будем гарантировать, что при появлении ошибки в native стороне, тут всегда будет не null значение, то ок.

2021-07-27 15:41 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
По-моему перемудрили слегка...

Зачем засовывать response в сессию? Ведь ответ не является атрибутом сессии, он возвращается в колбэке. К тому же, в виду того, что мы не можем сразу же получить от нативного кода ответ на searchByText, приходится на стороне dart генерировать sessionId, создавать объект сессии, чтобы вернуть его клиентскому коду. Сам response поступит позже и запихивать его в сессию не имеет смысла, тем более, что могут быть перезапросы из сессии, которые так же вернут свой ответ.

Потом не понял, зачем добавлять errorMsg в response? Во-первых это создаёт ряд неудобств - в частности, придётся сделать необязательными поля found и items. Я предлагаю обработку запроса не менять - оставить, как сейчас, onSearchResponse и onSearchError, а вот ссылки на эти колбэки должны переместиться в объект сессии:

final int id;
final SearchSessionCallback callback;
final SearchErrorCallback?  errorCallback;

В общем, запушил доработки - посмотрите. Один момент меня смущает, что из объекта сессии приходится обращаться к статическому свойству YandexSearch, чтобы удалить самого себя из коллекции.

2021-07-27 20:01 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    searchSession = searchManager.submit(
>Ведь ответ не является атрибутом сессии, он возвращается в колбэке. 

Почему нет? Колбеков не будет.

>Потом не понял, зачем добавлять errorMsg в response? Во-первых это создаёт ряд неудобств - в частности, придётся сделать необязательными поля found и items.

Что неудобного? Получил ответ. Если ошибка - делаем раз, если нет - два. Это удобнее, чем два колбека.

>Сам response поступит позже и запихивать его в сессию не имеет смысла, тем более, что могут быть перезапросы из сессии, которые так же вернут свой ответ.

Это хорошее замечание. Если закладываемся на перезапросы, то лучше сделать `Stream<SearchResponse> response`

2021-07-28 12:42 UTC, DCrow requested changes
Что-то калбэки все еще остались, хотя хотели уйти к Future
Кроме того один и тот же калбэк onSearchResponse теперь срабатыватывает при вызове любого метода сессии, чего совсем не ожидаешь(да и не всегда нужно).

2021-07-28 12:42 UTC, DCrow commented on lib/src/yandex_search_session.dart
> +  static const String _channelName = 'yandex_mapkit/yandex_search';
Тут надо по аналогии с `YandexMapController` при инициализации создавать новый id, и использовать в названии канала(а на native стороне) создавать аналогичный канал.

В этом случае `YandexSearch` не надо будет знать о всех созданных им сессий.

2021-07-28 12:42 UTC, DCrow commented on lib/src/yandex_search_session.dart
> +  final SearchSessionCallback callback;
В итоге опять вернулись к калбэкам, хотели же возвращать ответ всегда, где была бы и ошибка/ответ.
К тому же не пойму как это будет работать в ситуации, когда мы вызываем `fetchSearchNextPage`.
Явно же не хотим тот же callback вызвать.

2021-07-28 12:42 UTC, DCrow commented on ios/Classes/YandexSearch.swift
> +  private var searchSessions: [Int:YMKSearchSession] = [:]
Тут как и в dart создается впечатление, что было бы хорошо вынести логику работы с сессией в отдельный класс, который бы создавался при вызове `searchByText`

2021-07-28 13:29 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +  static const String _channelName = 'yandex_mapkit/yandex_search';
>  Тут надо по аналогии с YandexMapController при инициализации создавать новый id, и использовать в названии канала(а на native стороне) создавать аналогичный канал.

Хм, посмотрю, не обращал внимания, что так устроено. Я было тоже задумался, что каждой сессии нужен будет свой канал, но посчитал, что это слишком сложно..

2021-07-28 13:37 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +  final SearchSessionCallback callback;
Видимо, я не до конца уловил вашу идею - не видел обсуждения того, что колбэки больше не нужны. С fetchSearchNextPage - не совсем корректно получается, что один и тот же колбек вызывается. Но я всё равно не понял тогда, к чему вы хотите прийти...

2021-07-28 14:01 UTC, cream-cheeze commented
Не поймите меня неправильно, я благодарен за то, что такой плагин вообще есть, и большое спасибо за это. Но, я со своей стороны вижу ситуацию так: я ранее заводил issue, в котором спрашивал о наличии такого функционала, ты мне ответил, что его нет, времени на доработку тоже нет, но ты готов принять PR, и в общих чертах обрисовал, что это функционал в рамках Search. 
Я посмотрел, как работает getSuggestions и сделал в точности по аналогии, ну за исключением мульти-сессионности, потому что посчитал это излишним. В принципе, всё прекрасно работало, и свою собственную задачу я закрыл на 100%, при этом плагин был допилен максимально преемственным способом без "отсебятины". Без вопросов пофиксил косяки, небольшие пожелания по кодстайлу и т.п. Теперь же мы решаем всё вообще делать иначе, и хотелкам, кажется, нет конца и края. Я не был готов отвлекаться от основного проекта на такое продолжительное время, откровенно говоря.
Конечно же, я бросать это на полпути не собираюсь, и хочу, чтобы PR попал в основной репозиторий, но давайте тогда уже более конкретно опишем, чего хотим и каким должен быть финальный результат. Чтобы не было, как сейчас: тут переделай, там переделай, а колбэков, оказывается не должно быть, хотя до этого они были...

2021-07-28 14:11 UTC, DCrow commented
Понял вас, действительно, здесь уже сильно наплодили разных хотелок. 

Давай поступим таким образом - сделаем поддержку мульти-сессионности в точности как это работает в suggest. 
Это все соберем в репозиторий, и потом @ILAgent все три варианта(включая его PR #118) поправит, чтобы было однородно и так как мы обсудили выше.

Все остальное уже в отдельном Issue лучше обсуждать, иначе так этот PR никогда не приведем к завершению...

2021-07-28 14:39 UTC, cream-cheeze commented
Спасибо за понимание. 
Правда не уверен, что из текущей позиции это будет самый оптимальный вариант, так как в моей ветке уже всё вперемешку - и правки, и переработки. Если откачусь назад, то могу какие-то пофикшенные ошибки упустить. Давайте лучше кто-то из вас для меня более конкретно обрисует, что нужно поменять, а я уж допилю. Ну а потом @ILAgent причешет, если что.
Я понял, что вы решили отказаться от колбэков и возвращать результат каким-то образом прямо в сессию? Вот здесь поподробнее хочется - как это должно выглядеть, у @ILAgent в его ветке есть уже что-то подобное? Как будут дополнительные результаты по сессии приходить? Там что-то @ILAgent про стримы писал...

2021-07-28 14:46 UTC, ILAgent commented
>Вот здесь поподробнее хочется - как это должно выглядеть, у @ILAgent в его ветке есть уже что-то подобное?

Да, роутер я сделал как раз так.

>Как будут дополнительные результаты по сессии приходить? Там что-то @ILAgent про стримы писал...

Вот тут надо подумать. Возможно да, что-то со стримами, но сейчас не готов предложить решение.

2021-07-28 14:49 UTC, ILAgent commented
>Давайте лучше кто-то из вас для меня более конкретно обрисует, что нужно поменять, а я уж допилю. 

Тогда и саджест тебе допиливать, чтобы не было разных подходов в мастере) Либо ждать, пока я допилю и замёржусь.

2021-07-28 14:51 UTC, cream-cheeze commented
> > Давайте лучше кто-то из вас для меня более конкретно обрисует, что нужно поменять, а я уж допилю.
> 
> Тогда и саджест тебе допиливать, чтобы не было разных подходов в мастере) Либо ждать, пока я допилю и замёржусь.

Да ладно, чё такого - независимый друг от друга функционал, главное, что всё рабочее. Тем более, чтобы народ начал юзать, нужно версию новую снять.

2021-07-28 15:02 UTC, ILAgent commented
> Да ладно, чё такого - независимый друг от друга функционал, главное, что всё рабочее. Тем более, чтобы народ начал юзать, нужно версию новую снять.

Вообще согласен, мастер - это рабочая ветка по идее, не релиз.

2021-07-28 15:16 UTC, cream-cheeze commented
> В проектах, где есть уверенность, что далее тот или иной функционал будет дорабатываться да. А в таких, которые более менее нишевые, лучше до конца сразу завершать, иначе потом так и останется висеть не до конца доделанным...

Речь не об этом, а о том, что может оказаться небольшой временной лаг, когда ветка с поиском уже будет в мастере, а садджесты ещё будут дорабатываться (но точно будут).

2021-07-28 15:39 UTC, cream-cheeze commented
> > Вот здесь поподробнее хочется - как это должно выглядеть, у @ILAgent в его ветке есть уже что-то подобное?
> 
> Да, роутер я сделал как раз так.
> 
> > Как будут дополнительные результаты по сессии приходить? Там что-то @ILAgent про стримы писал...
> 
> Вот тут надо подумать. Возможно да, что-то со стримами, но сейчас не готов предложить решение.

Вот об этом вы, я так понимаю? Вместо колбэков... 

```
final futureRoutes = _channel
        .invokeMethod('requestRoutes', request)
        .then((resultRoutes) => _mapSessionResult(resultRoutes));
```

Я думал, так нельзя...  Это круто, что можно. Тогда всё более-менее проясняется.

Со страницами - предлагаю тогда усложнить структуру ответа - добавить туда сущность страницы. Номера страниц на стороне нативного кода инкрементировать и передавать номер страницы вместе с ответом. Тогда в сессии у нас будет храниться постраничный результат.

2021-07-28 17:26 UTC, cream-cheeze commented
Хочу проговорить, чтобы убедиться, что всё правильно понимаю...

1. [flutter] Делаю, как и сейчас, запрос searchByText в классе YandexSearch, который отправляет сообщение в канал yandex_mapkit/yandex_search.
2. [ios/android] Вызывается поиск, который возвращает mapkit-сессию.
3. [ios/android] Создаю отдельный объект для работы с сессией, в котором сохраняю ссылку на только что созданную mapkit-сессию. Здесь генерирую id сессии и создаю отдельный канал yandex_mapkit/yandex_search_session_{id}.
4. [ios/android] Возвращаю во флаттер данные созданной сессии вместе с первой страницей поиска через Future.
5. [flutter] Создаю объект сессии из полученных данных, и поднимаю канал на основании id-сессии.
6. [flutter] Далее из сессии общаюсь с нативным кодом через индивидуальный канал.

Всё так?

2021-07-28 19:34 UTC, ILAgent commented
Словами как-то сложно :) Получится сделать, как в маршрутах? Каналы на сессию там не создаются.

2021-07-28 21:01 UTC, cream-cheeze commented
> Словами как-то сложно :) Получится сделать, как в маршрутах? Каналы на сессию там не создаются.

Пока не успел досконально изучить, поэтому могу ошибаться, но, насколько я понял, маршруты немного иначе устроены - там есть YandexDrivingRouter, который рулит сессиями и общается с флаттером по своему выделенному каналу yandex_mapkit/yandex_driving, а здесь же мы решили, что вводим самостоятельный объект сессии, который инкапсулирует всю логику работы внутри себя, и таких сессий может быть одновременно сколько угодно много. 

Чтобы сообщения не перемешались, варианта вижу два: делать на каждую сессию по каналу, как @DCrow [выше](https://github.com/Unact/yandex_mapkit/pull/119#discussion_r678256366) предложил, или вести широковещательную передачу сообщений внутри одного канала, и каждая сессия должна будет проверять, относится ли сообщение к ней или нет. Последнее менее изящно.

2021-07-29 12:44 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +  private var searchSessions: [Int:YMKSearchSession] = [:]
Я тут немного встрял, есть нюансы непонятные...

Сессию нужно создавать сразу после того, как submit вернул новую mapkit-сессию, чтобы сразу была возможность с ней работать - например, отменить запрос.
В этом случае получается, что результата ещё нет, и сессию мы создаём пустую - без результатов. Когда колбэк с результатом отработает, результат нужно будет передать в уже созданную сессию, чтобы она в свою очередь через стрим вернула результат в flutter.
Проблема здесь в том, что и YandexSearch и YandexSearchSession должны уметь обрабатывать результат поиска, YandexSearch - первого, YandexSearchSession - последующих. Получается дублирование функционала.

Есть мысли на этот счёт?

2021-07-29 15:44 UTC, cream-cheeze commented
Короче, я реально пытался, но пришёл к следующим выводам:

1. Конечно, взаимодействие между flutter и нативным кодом удобнее и изящнее через Future, нежели чем через цепочку двунаправленных вызовов. Так, я, например, переделал вызов searchByText, который теперь возвращает Future<SearchSession>.

2. Но, в отличие от DrivingRouter поиск устроен сложнее за счёт того, что результат может запрашиваться постранично. По этой причине сделать так же не получится, и в случае с поиском, как я и писал ранее, отчётливо видно, что Response - не совсем атрибут сессии - во-первых потому, что сессия создаётся до появления ответа, а во-вторых потому, что ответ может дополняться новыми страницами или замещаться.

3. Для решения с пагинацией @ILAgent предложил задействовать стримы – я изучил эту возможность, и даже уже реализовал, но только погодя понял, что: во-первых это избыточно в данном случае (стрим хорош, когда ты ожидаешь ответ, но не знаешь точно когда он может прийти - в нашем же случае ответ является реакцией на действие: поиск, запрос новой страницы или уточняющий запрос), а во-вторых это сложно для пользователя - не будем же мы выставлять ему стрим наружу, и заставлять на него подписываться. Будет выглядеть так: вызвал searchByText -> подписался на стрим -> получил в стрим первую страницу -> вызвал fetchNextPage -> получил в стрим новую страницу. Сложно.

В общем, конкретно в данном случае, схема с колбэками выглядит более логичной и жизнеспособной. Можно, в принципе, избавиться от колбэков внутри плагина (при общении между flutter и ios/android можно использовать EventChannel для передачи страниц - вместо invokeMethod("onSearchResponse"), хотя это тоже спорно), но пользователю гораздо понятнее будет получить возможность передавать callback, который будет вызываться и при первом поиске, и при запросе страниц - просто в ответе будет содержаться атрибут page. Колбэки onResponse и onError можно объединить, как предлагалось.

2021-08-02 09:22 UTC, DCrow commented
Насчет общего калбэка для поиска и пагинации, спорный момент. 
Далеко не всегда хочется делать одно и тоже, а заставлять юзера проверять что за страница тоже как-то не правильно. 
Кажется что при получении новой страницы часто хочется что-то другое сделать, но уже одинаковое для всех последующих(кроме может последней).
Но что-то не могу найти вариант лучше чем использовать один калбэк.

Согласен что вариант со стримами выглядит сложнее, но вариант с калбэками в данном случае плохо расширяется(в плане работы с пагинацией). Есть еще вариант, как в #118, который по проще, но не использует калбэки.

Тогда схема тут будет выглядеть следующим образом
1. Вызывается метод searchByText, вместе с ним создается сессия и вызывается метод на native стороне.
2. Возвращается объект сессии, где results это future, который и есть ответ вызова метода из 1 пункта
3. Пользователь ждет когда results разрешится. 
4. После разрешения results, пользователь проверяет isError и в случае null, то считаем что ответ успешный и можно считывать значение из results.
5. Далее пользователь пользуется все той же сессией для получения последующих результатов, по аналогии с 4 пунктом.

Так получаем, что все фичи будут иметь одинаковую структуру взаимодействия с ними(Сначала проверить есть ли ошибка, а потом использовать результат)

Очень понравился вариант со стримами, но да, какое-то получается очень сложное взаимодействие. 
Тут бы еще хотел услышать @ILAgent, так как на мой взгляд функционал в либе должен иметь одну форму взаимодействия, и крайне сильно не хотелось бы иметь две разные формы(стримы/калбэки и future + проверка на ошибку)

2021-08-02 09:45 UTC, cream-cheeze commented
> После разрешения results, пользователь проверяет isError и в случае null, то считаем что ответ успешный и можно считывать значение из results.
> Далее пользователь пользуется все той же сессией для получения последующих результатов, по аналогии с 4 пунктом.
> Так получаем, что все фичи будут иметь одинаковую структуру взаимодействия с ними(Сначала проверить есть ли ошибка, а потом использовать результат)

Блин, не в том ревью я этот комментарий хотел оставить... Ну ладно...

Что касается ошибок - что в стримах, что во фьючерах есть механизм обработки ошибок: onError или catchError - я бы использовал его, как я и сделал в serach2. Это позволяет не изменять структуру searchResponse и не добавлять в него ошибку - более красивое решение, на мой взгляд.

По поводу последующих результатов уже не совсем понятно... Вот у нас есть сессия от searchByText и есть первая страница, которая содержится в results (который Future<SearchResults>). А что дальше - дёргаем fetchNextPage - он должен вернуть тоже Future<SearchResults> уже с новой страницей?

2021-08-02 09:58 UTC, ILAgent commented
>Тут бы еще хотел услышать @ILAgent, так как на мой взгляд функционал в либе должен иметь одну форму взаимодействия

Да, я сегодня очень постараюсь внимательно посмотреть и отпишусь.

> А что дальше - дёргаем fetchNextPage - он должен вернуть тоже Future уже с новой страницей?

Да, future нельзя переиспользовать для разных результатов. Когда результатов много - это как раз стрим. Но хз, насколько это удобно.

2021-08-02 10:03 UTC, cream-cheeze commented
> Да, future нельзя переиспользовать для разных результатов. Когда результатов много - это как раз стрим. Но хз, насколько это удобно.

Ну вот в таком случае логика и здравый смысл подсказывают, что results - это не атрибут сессии. Странно получается - в первом случае мы читаем результат из поля сессии, а при получении следующей страницы нам его отдаёт уже функция. Но при первом поиске мы не можем так же сделать, потому что должны сессию вернуть. Короче здесь явно напрашиваются либо стрим, либо колбэки...

2021-08-02 10:04 UTC, cream-cheeze commented
Да, я сегодня очень постараюсь внимательно посмотреть и отпишусь.

Давайте только продолжать в соседнем PR, плиз, а то мы и тут и там...

2021-08-02 12:27 UTC, DCrow commented
> Что касается ошибок - что в стримах, что во фьючерах есть механизм обработки ошибок: onError или catchError - я бы использовал его, как я и сделал в serach2. Это позволяет не изменять структуру searchResponse и не добавлять в него ошибку - более красивое решение, на мой взгляд.

Действительно, лучше его использовать.

> По поводу последующих результатов уже не совсем понятно... Вот у нас есть сессия от searchByText и есть первая страница, которая содержится в results (который Future). А что дальше - дёргаем fetchNextPage - он должен вернуть тоже Future уже с новой страницей?

Да, думаю юзер сам должен хранить результаты первой страницы, ровно также как и нативная либа требует. 

> Да, future нельзя переиспользовать для разных результатов. Когда результатов много - это как раз стрим. Но хз, насколько это удобно.

Так никто же не запрещает поле делать final. Можно же новый future создать и его отдать. Стрим тут как-то все сильно усложняет.

2021-09-02 13:57 UTC, DCrow commented
Закрываю в пользу #127

2021-09-02 13:57 UTC, closed without merging