fix mapkit initialization
Unact/yandex_mapkit pull request #125
Opened 2021-07-24 08:56 UTC by ILAgent

#96

2021-07-28 14:50 UTC, ILAgent commented
@DCrow глянь плз)

2021-07-28 15:08 UTC, DCrow requested changes
Пару моментов нашел, в целом выглядит хорошо

2021-07-28 15:08 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +    MapKitFactory.initialize(binding.getApplicationContext());
Тогда и SearchFactory тоже надо тут инициализировать.

2021-07-28 15:08 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
>  public class YandexMapkitPlugin implements FlutterPlugin {
Тут мне казалось надо добавлять ActivityAware и его ивенты тоже имплементировать, чтобы андроид действительно корректно начал реагировать.

2021-07-28 15:08 UTC, DCrow commented on ios/Classes/SwiftYandexMapkitPlugin.swift
> +    YMKMapKit.sharedInstance().onStart()
Что-то не видел такого в примерах Яндекса.
Оно действительно помогает?

Может на init/deinit добавить onStart/onStop?

2021-07-28 18:44 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +    MapKitFactory.initialize(binding.getApplicationContext());
Почему? Тут мы инициализируем сам мапкит, а отдельные части - по местам использования. Кажется логично.

2021-07-28 18:51 UTC, ILAgent commented on ios/Classes/SwiftYandexMapkitPlugin.swift
> +    YMKMapKit.sharedInstance().onStart()
>Оно действительно помогает?

Да, без этого не работает

>Может на init/deinit добавить onStart/onStop?

Не в курсе, как это сделать, в ios не шарю и сходу не нашёл в доках. Подскажешь?

2021-07-28 19:19 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
>  public class YandexMapkitPlugin implements FlutterPlugin {
Для мапкита не нужна активити

2021-07-29 08:10 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +    MapKitFactory.initialize(binding.getApplicationContext());
Тут и Search тоже иницализируется. 
На мой взгляд тут вся инициализация должна лежать, не зависимо от части мапкита.(К тому же, если бы у `SearchFactory.getInstance()` был метод onStart, то только тут бы и использовали его.)

2021-07-29 08:11 UTC, DCrow commented on ios/Classes/SwiftYandexMapkitPlugin.swift
> +    YMKMapKit.sharedInstance().onStart()
Что-то вроде такого
```swift
import CoreLocation
import Flutter
import UIKit
import YandexMapsMobile

public class SwiftYandexMapkitPlugin: NSObject, FlutterPlugin {

  public static func register(with registrar: FlutterPluginRegistrar) {
    registrar.register(
      YandexMapFactory(registrar: registrar),
      withId: "yandex_mapkit/yandex_map"
    )
    
    YandexSearch.register(with: registrar)
  }

  public override init() {
      super.init()
      YMKMapKit.sharedInstance().onStart()
  }
  
  deinit {
      YMKMapKit.sharedInstance().onStop()
  }
}
```

2021-07-29 19:26 UTC, ILAgent commented on ios/Classes/SwiftYandexMapkitPlugin.swift
> +    YMKMapKit.sharedInstance().onStart()
Попробовал, так не работает. Видимо, экземпляр нигде не создаётся.

2021-07-29 19:30 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +    MapKitFactory.initialize(binding.getApplicationContext());
Я рассуждаю так. SearchFactory - это зависимость только YandexSearchHandlerImpl, не всего плагина. Если мы вдруг выкинем YandexSearchHandlerImpl - инициализация SearchFactory выкинется вместе с ним. А если по-твоему, то SearchFactory.getInstance() останется.

2021-08-02 07:38 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +    MapKitFactory.initialize(binding.getApplicationContext());
Согласен с тобой, что было бы хорошо иметь все в YandexSearchHandlerImpl, но проблема, что только класс YandexMapkitPlugin знает о onAttachedToEngine/onDetachedFromEngine и получается что только отсюда можем вызвать(если бы они были) SearchFactory.getInstance().onStart()/ SearchFactory.getInstance().onStop()

Я больше смотрю на этот класс как инициализатор, где запускаются все части либы, как YandexMapFactory, так и YandexSearchHandlerImpl.

2021-08-02 10:46 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +    MapKitFactory.initialize(binding.getApplicationContext());
>Я больше смотрю на этот класс как инициализатор, где запускаются все части либы, как YandexMapFactory, так и YandexSearchHandlerImpl.

А какая в этом практическая польза? Минус - увеличивается связность, как я писал выше.

>но проблема, что только класс YandexMapkitPlugin знает о onAttachedToEngine/onDetachedFromEngine и получается что только отсюда

Сейчас да, но это может измениться при желании. 

В общем момент не сильно принципиальный, а обсуждение долгое. Если ты всё же настаиваешь - подтверди, я перенесу.

2021-08-02 12:10 UTC, merged

2021-08-05 09:13 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> -  public static void registerWith(Registrar registrar) {
Хмм, оказывается flutter уже начал поддержку рубить https://github.com/flutter/flutter/issues/86578
Наверное, тоже лучше пойти таким путем, убрать функционал, оставить коммент про это в README и полагаться на ошибки, которые flutter будет выдавать