Search2
Unact/yandex_mapkit pull request #127
Opened 2021-07-29 17:06 UTC by cream-cheeze

Сделал новым PR, так как в предыдущем уже теряешься, ну и это экспериментальная версия на обсуждение.

2021-07-29 17:17 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
Здесь узкий момент - "наша" сессия создаётся после мэпкитовой, и если responseHandler выполнится раньше, чем "наша" сессия инициализируется здесь и на стороне flutter, то нихрена не работает – т.е. ответ приходит раньше, чем поднимается канал для обмена данными. Можно наглядно увидеть, если поставить на этой строке брейкпоинт.

Вот хочу посоветоваться, проблема это или нет? Склоняюсь к тому, что проблема, хотя, если выполнение программы не тормозить искусственно, то даже и не знаю - может ли случиться, что responseHandler отработает раньше? 

Можно попытаться решить, создавая сессию сразу на стороне flutter (как обычно. генерить sessionId в Dart и передавать сюда), а здесь - создавать YandexSearchSession тоже до вызова submit, а после вызова добавлять YMKSearchSession. Но это менее красивый вариант, да и не лишённый проблем – в частности, если сессия поднята на стороне flutter ещё до ответа от searchByText, то кто-то может попытаться к ней обратиться, а её ещё нет по факту... В общем нужно решить, как здесь быть....

2021-07-29 17:19 UTC, cream-cheeze commented on example/lib/examples/search_page.dart
> +      // onSearchResponse: (SearchResponse res, int sessionId) {
Здесь я бы предложил оставить колбэк (сейчас, в этой ветке, просто печатается результат в самом плагине, пользователю ничего не отдаётся).

2021-07-29 17:21 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
Здесь тоже не очень нравится - пришлось сделать статический ассоциативный массив, чтобы где-то хранить созданные сессии. К этому массиву приходится обращаться из YandexSearchSession при удалении сессии. Возможно, есть лучше решение, но я не увидел..

2021-07-29 17:25 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +    final session = _channel.invokeMethod(
Вот здесь проявляется та же проблема, которую описал в swift-файле - если здесь выполнение притормозить, поставив, например, брейкпоинт внутри _mapSessionResult, то на стороне Swift успевает отработать поисковый колбэк, и в этом случае результат не будет передан во flutter.

2021-07-29 17:38 UTC, cream-cheeze commented
@DCrow @ILAgent посмотрите, пожалуйста! Очень хочется с этим покончить, как можно скорее...

2021-07-29 19:38 UTC, ILAgent commented on lib/src/types/search_response.dart
> +  final int?                found;
Зачем это, если можно посмотреть размер списка?

2021-07-29 19:40 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +    _methodChannel = MethodChannel(_methodChannelName + id.toString());
А каналы где-то должны закрываться?  Или умирают вместе с сессией?

2021-07-29 19:42 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +  MethodChannel? _methodChannel;
почему nullable?

2021-07-29 19:43 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +    await _methodChannel!.invokeMethod<void>('cancelSearch');
кажется можно же через один канал, предавая id сессии

2021-07-29 19:54 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +    print(respObj);
а где он клиенту возвращается?

2021-07-29 20:13 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +    await _methodChannel!.invokeMethod<void>('cancelSearch');
Можно, только в этом случае все сессии будут получать каждое сообщение, а так только конкретная. Думаю, этот более элегантное решение.

2021-07-29 20:15 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +    print(respObj);
Это не финальная версия. [Выше](https://github.com/Unact/yandex_mapkit/pull/127#discussion_r679343981) написал об этом.

2021-07-29 20:18 UTC, cream-cheeze commented
Хочется получить комментарии по принципиальным моментам, которые обозначил в этом ревью, ну или которые вы ещё увидите. Цель — договориться о финальной архитектуре. Получившееся решение не идеально, в предыдущие обсуждения не все нюансы были учтены. Мелочи вроде nullable предлагаю позже обсуждать.

2021-07-29 20:19 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +    _methodChannel = MethodChannel(_methodChannelName + id.toString());
В канал отправляется завершающий сигнал при закрытии сессии — этого должно быть достаточно, по идее, но не уверен.

2021-07-29 20:20 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +  final int?                found;
Хз, Яндекс это поле возвращает, я продублировал - думал, что это общий размер списка без пагинации, но оказалось, что нет.

2021-07-30 17:30 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +  final int?                found;
Опытным путём выяснил, что found увеличивается с каждой запрошенной страницей - это сколько всего записей уже вернулось, включая предыдущие страницы.

2021-07-30 18:05 UTC, cream-cheeze commented
Вообщем, пока ждал ответа, закончил эту версию – в результате в SearchSession сделал стрим results, на который можно подписаться и получать новые результаты по мере их поступления. 

Честно говоря, всё это выглядит чрезмерно усложнённым, и стримы здесь кажутся явно лишними. Мой самый первый вариант с одной сессией на колбэках был самым простым в использовании и самым понятным... Здесь куча нюансов: нужно получить сессию, потом не забыть закрыть ёё, подписаться на стрим, потом отписаться. Короче каша какая-то, на мой взгляд.

Но если уж мультисессионность так принципиальна,  то я бы лучше взял вот эту последнюю мою версию, выпилил бы оттуда нафиг этот стрим, и вернул бы колбэки с результами.

Варианты с колбэками:
1. Передавать один колбэк в searchByText и сохранять его в сессии - вызывать при каждом _onResponse. Получается, что этот единственный колбэк будет срабатывать: при первом вызове searchByText, при fetchNextPage и при retrySearch. Способ обработки будет зависеть от номера страницы в ответе.
2. Передавать разные колбэки в каждый из вышеперечисленных методов. Но смысла в этом мало - в каждом из случаев возвращается одна и та же структура данных, и обработка будет одна и та же.

Я за первый вариант.

@DCrow  ответь, пожалуйста, давай уже решим что-нибудь.

2021-07-30 18:16 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
Всё-таки, думаю, что это нормальное поведение - не бага. Я про то, что если тормозится выполнение основного потока дебаггером, то колбэк успевает отработать параллельно, что приводит к нарушению в функционировании программы. При штатном исполнении такого не должно происходить.

2021-08-02 09:24 UTC, DCrow requested changes
Очень понравилось использование стримов! 
Некоторые моменты надо бы поправить. 
Но сначала надо бы договорится в https://github.com/Unact/yandex_mapkit/pull/119#issuecomment-890871695, чтобы напрасно не делать работу.

На сколько я понял Android пока не имплементирован?

2021-08-02 09:28 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +  Future<void> closeSession() async {
Да, согласен - это тянется из предыдущей реализации, где это было важным отличием от suggestions. Вроде везде избавлялся, а тут пропустил.

2021-08-02 09:29 UTC, cream-cheeze commented on ios/Classes/YandexSearchSession.swift
> +  public func fetchNextPage() {
Ок

2021-08-02 09:32 UTC, cream-cheeze commented on ios/Classes/YandexSearchSession.swift
> +    YandexSearch.searchSessions[id] = nil
Вроде в свифте для Dictionary это равнозачно removeValue. Если я даже ошибаюсь, то останется только пустой элемент, ссылка на объект убьётся.

2021-08-02 09:32 UTC, cream-cheeze commented on ios/Classes/YandexSearchSession.swift
> +//
Ок

2021-08-02 09:32 UTC, cream-cheeze commented on lib/src/types/callbacks.dart
> +typedef SearchErrorCallback = void Function(String msg, int sessionId);
Ок

2021-08-02 09:38 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
> Так мы не обязаны отдавать сессию сразу при вызове searchByText. Мы можем создать объект, отправить запрос и после этого уже вернуть созданный объект, который уже может и иметь ответ(а может и не иметь, в зависимости от того как быстро вернет ответ responseHandler

По-хорошему стоило бы это делать, так как сразу после создания нативной сессии, её можно, например, отменить, а мы в таком случае, получается, блокируем такую возможность. Как только сессия появилась - с ней можно работать.

2021-08-02 09:39 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
Ну есть вариант такой: сделать внутри сессии импровизированную "очередь" - если результат колбэка придёт раньше возврата session, то можно засетить результат в эту очередь, а когда это будет возможно, сессия отправит этот результат и обнулит очередь.

2021-08-02 09:47 UTC, cream-cheeze commented on example/lib/examples/search_page.dart
> +    // print('Cancel search');
Кнопку не успеет нажать никто. Я могу просто убрать это, если тебе это прям не даёт покоя ) Хотя я не раз видел подобные примеры, где часть кода закоменчена.

2021-08-02 09:49 UTC, cream-cheeze commented on example/lib/examples/search_page.dart
> +    // print('Cancel search');
> На сколько я понял Android пока не имплементирован?

Да, Android не делал, чтобы зря время не тратить.

2021-08-02 09:57 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
> Мне кажется что race-condition всегда плохо, если бы больше вариантов не было бы, тогда ок, но тут же есть более лучшее решение.

По-моему, это не совсем race-condition, если это может случиться только при работе дебаггера - обработка колбэка не останавливается. Как раз-таки это логичное поведение, и программист, который дебаггером пользуется, должен это понимать. Race-condition это когда результат неопределён и приводит к "моргающим" багам.

2021-08-02 09:59 UTC, cream-cheeze commented on ios/Classes/YandexSearchSession.swift
> +    YandexSearch.searchSessions[id] = nil
Нет, не равнозначно - removeValue ключ тоже удаляет. Поправлю.

2021-08-02 10:12 UTC, cream-cheeze commented
> На сколько я понял Android пока не имплементирован?

Да, Android не делал, чтобы зря время не тратить.

2021-08-02 12:23 UTC, DCrow commented on example/lib/examples/search_page.dart
> +    // print('Cancel search');
Давай лучше уберем. Плохой пример получается на мой взгляд.

Запрос отрабатывает за доли секунды, потому что обычно при разработке хорошая связь. В реальных условиях же, связь может быть совсем плохая(а может и вообще не быть). С таким примером сложно понять, как использовать этот метод.

2021-08-02 12:28 UTC, DCrow commented
В продолжение диалога https://github.com/Unact/yandex_mapkit/pull/119#issuecomment-890897257 

> Что касается ошибок - что в стримах, что во фьючерах есть механизм обработки ошибок: onError или catchError - я бы использовал его, как я и сделал в serach2. Это позволяет не изменять структуру searchResponse и не добавлять в него ошибку - более красивое решение, на мой взгляд.

Действительно, лучше его использовать.

> По поводу последующих результатов уже не совсем понятно... Вот у нас есть сессия от searchByText и есть первая страница, которая содержится в results (который Future). А что дальше - дёргаем fetchNextPage - он должен вернуть тоже Future уже с новой страницей?

Да, думаю юзер сам должен хранить результаты первой страницы, ровно также как и нативная либа требует. 

> Да, future нельзя переиспользовать для разных результатов. Когда результатов много - это как раз стрим. Но хз, насколько это удобно.

Так никто же не запрещает поле делать final. Можно же новый future создать и его отдать. Стрим тут как-то все сильно усложняет.

2021-08-02 16:04 UTC, ILAgent commented
Мне кажется, что стрим - это ок. Стрим эмитит очередную страницу после каждого фетча. При подписке сразу эмитится последняя полученная страница.
Ничего лучше в голову не приходит. И вроде бы вполне понятное апи.

2021-08-02 16:12 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +      methodChannel.invokeMethod("onSearchListenerResponse", arguments);
Зачем вызывать внешний метод? Почему не вернуть через Result?

2021-08-02 16:13 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +      methodChannel.invokeMethod("onSearchListenerResponse", arguments);
забыл, что андроид не доделан

2021-08-02 16:17 UTC, ILAgent commented on ios/Classes/YandexSearchSession.swift
> +      name: "yandex_mapkit/yandex_search_session_\(id)",
так и не понял, зачем плодить каналы, а не использовать общий канал поиска

2021-08-02 16:18 UTC, cream-cheeze commented on ios/Classes/YandexSearchSession.swift
> +      name: "yandex_mapkit/yandex_search_session_\(id)",
Чтобы можно было передавать сообщения без указания sessionId - классно же.

2021-08-02 18:08 UTC, cream-cheeze commented
@DCrow так что в итоге, как делаем? Твоя репа - тебе решать.

2021-08-02 19:51 UTC, ILAgent commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
Это самый настоящий race-condition. И дебагер это выявляет. Так точно нельзя оставлять имхо.  В такой реализации нет этой проблемой https://github.com/Unact/yandex_mapkit/pull/118/files#diff-60e6392db351c52aac0a99106359179ec18339afc0d14404e1801b1961e237f5

2021-08-02 19:53 UTC, ILAgent commented on lib/src/types/search_response.dart
> +  final int?                found;
Насколько я помню, found должна возвращать сколько вообще найдено результатов, на всех страницах. Но могу ошибаться.

2021-08-02 19:54 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +  MethodChannel? _methodChannel;
тут не late, а через инициализаторы

2021-08-02 19:57 UTC, ILAgent commented
> > Что касается ошибок - что в стримах, что во фьючерах есть механизм обработки ошибок: onError или catchError - я бы использовал его, как я и сделал в serach2. Это позволяет не изменять структуру searchResponse и не добавлять в него ошибку - более красивое решение, на мой взгляд.
> 
> Действительно, лучше его использовать.

Мы же договорились не превращать мапкитовые ошибки в дартовые эксепшены. Так-то у future тоже есть onError.

2021-08-02 20:01 UTC, ILAgent commented
> Мне кажется, что стрим - это ок. Стрим эмитит очередную страницу после каждого фетча. При подписке сразу эмитится последняя полученная страница.
> Ничего лучше в голову не приходит. И вроде бы вполне понятное апи.

Попроще вариант - `fetchNextPage(): Future<Response>`. Да, у сессии есть response и тут. Но зато сразу понятно, что к чему. Имхо)

2021-08-02 20:07 UTC, ILAgent commented on lib/src/yandex_search.dart
> +    _channel.setMethodCallHandler(_handleMethodCall);
не нужно

2021-08-02 20:09 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +    _streamController.sink.addError(arguments);
ошибки мапкита возвращаем через поля ответа

2021-08-02 20:13 UTC, ILAgent commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
нет удаления сессий

2021-08-02 20:16 UTC, ILAgent commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
А, увидел, из другого класса... Ну это как-то не очень. Тут должно быть private вместо static и удаление тут же.

2021-08-02 20:19 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +class SearchSession {
Для наглядности хорошо отделить интерфейс `abstract class SearchSession` от реализации `class SearchSession`. Чтобы было видно апи.

2021-08-02 20:26 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +  final int?                found;
Ну так и работает, толко это число увеличивается по мере запроса страниц, а не сразу отдаёт количество всех записей.

2021-08-02 20:30 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
Ну почему же прям самый настоящий? Ты видишь, как может то же самое случиться, если не включать дебаггер?

Ты же вроде предлагал стрим использовать, а теперь всё-таки за фьючи через сессию? И опять мы по кругу сейчас пойдём - я скажу, что response с адресами это не атрибут сессии, что есть ещё другие страницы...

2021-08-02 20:31 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +  MethodChannel? _methodChannel;
Можешь показать на примере? Это через двоеточие после конструктора?

2021-08-02 20:34 UTC, cream-cheeze commented
> Мы же договорились не превращать мапкитовые ошибки в дартовые эксепшены. Так-то у future тоже есть onError.

Я может чего не знаю.. А в чём минусы? Удобно же - использовать для ошибок специально предусмотренный для этого механизм языка, благодаря чему можно не уродовать класс ответа.

2021-08-02 20:36 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +class SearchSession {
Какой смысл, если не предвидятся какие-то иные имплементации данного интерфейса? На мой взгляд, это чрезмерно - интерфейс ради интерфейса..

2021-08-02 20:41 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
В смысле сделать публичный метод удаления из приватного статического массива?

2021-08-02 20:43 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
Если это свойство будет не static, то придётся в сессию передавать ссылку на YandexSearch, чего совсем не хотелось бы делать. Команда закрытия сессии приходит в класс сессии, и мы вынуждены обратиться к YandexSearch - больше ссылки на сессии негде хранить.

2021-08-02 20:45 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +    _streamController.sink.addError(arguments);
Не понял

2021-08-02 20:50 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +    _channel.setMethodCallHandler(_handleMethodCall);
Ну как? В мастере, от которого я создавал ветку, хэндлер устанавливается в методе _getSuggestions. Пришлось и в searchByText сделать то же самое, хотя согласен, что не красиво. Нужно тогда выносить в конструктор.

2021-08-02 20:59 UTC, cream-cheeze commented
> > Мне кажется, что стрим - это ок. Стрим эмитит очередную страницу после каждого фетча. При подписке сразу эмитится последняя полученная страница.
> > Ничего лучше в голову не приходит. И вроде бы вполне понятное апи.
> 
> Попроще вариант - `fetchNextPage(): Future<Response>`. Да, у сессии есть response и тут. Но зато сразу понятно, что к чему. Имхо)
> Переиспользовать свойство response сесии как-то очень неочевидно.

Переиспользовать свойство response сесии - совсем неочевидно, согласен. Но для меня так же неочевидно первый результат получать из сессии, а последующие напрямую от выполнения функций. Помимо следующей страницы может быть такая ситуация: вызвали searchByText, создалась и вернулась сессия, а при получении результата возникла ошибка - на этот случай есть метод retry - он тоже будет Future<SearchResponse> возвращать, несмотря на то, что это будет первая страница? Крайне запутанно. 

Все результаты от всех этих методов нужно возвращать одним способом - и самый лучший способ видится колбэками, т.к. стрим здесь не в кассу (он искусственный), а фьючи не получается сделать в одном ключе из-за того, что searchByText возвращает сессию, а не ответ. Не даром в mapkit все эти методы принимают абсолютно одинаковый responseHandler, который одинаковым образом обрабатывает результат.

2021-08-02 21:10 UTC, cream-cheeze commented on example/lib/examples/search_page.dart
> +    // print('Cancel search');
Убрал

2021-08-03 07:19 UTC, DCrow commented on ios/Classes/YandexSearch.swift
> +    let session = YandexSearchSession(id: sessionId, session: searchSession, registrar: pluginRegistrar)
> Ну есть вариант такой: сделать внутри сессии импровизированную "очередь" - если результат колбэка придёт раньше возврата session, то можно засетить результат в эту очередь, а когда это будет возможно, сессия отправит этот результат и обнулит очередь.

Что-то ты тут сильно усложнять пытаешься. Можно делать следующим образом. Внутри метода searchByText:
1. Создаем объект сессии на стороне дарт
2. Отправляем запрос на native сторону.
3. Возвращаем объект сессии.

Тут необязательно везде await использовать, 2 будет future, который в сессии что либо вернет. Тут ты верно подмечаешь, что если использовать стрим, то можно не успеть прослушать результат(так как future на native  может выполнится ранее). Поэтому получаем что единственный вариант это использование Future. С калбэками уже говорили, что они не подходят из-за пагинации.

> response с адресами это не атрибут сессии
Да на native стороне так и есть, но к сожалению, на dart стороне мы не можем идеально воспроизвести native, поэтому такие извороты и получаются.

2021-08-03 07:21 UTC, DCrow commented on lib/src/types/search_response.dart
> +  final int?                found;
Если они различаются, то пусть остается. Для кого-нить явно будет полезным. Например понять, сколько записей уже просмотрел(чтоб во всякие платежные лимиты не попасть).

2021-08-03 07:24 UTC, DCrow commented on lib/src/yandex_search_session.dart
> +  MethodChannel? _methodChannel;
Да, можно и через иницилизаторы(выглядит конечно очень не красиво)
```dart
SearchSession({required this.id}) : 
  _methodChannel = MethodChannel(_methodChannelName + id.toString()),
  _eventChannel  = EventChannel(_eventChannelName + id.toString()) 
{
  _eventChannel.receiveBroadcastStream().listen(_onResponse, onError: _onError);
}
```

2021-08-03 07:28 UTC, DCrow commented on lib/src/yandex_search.dart
> +    _channel.setMethodCallHandler(_handleMethodCall);
Да тут @ILAgent прав, тут же каллбэков нет. 
В Suggestions же они есть, там он поэтому и нужен.
Метод же делает, что настраивает канал, чтобы он смог принять вызовы из native стороны. А в searchByText из native ничего не вызывает канал `yandex_mapkit/yandex_search`

2021-08-03 07:30 UTC, DCrow commented on lib/src/yandex_search_session.dart
> +class SearchSession {
Тоже согласен с @cream-cheeze, одно дело если бы его потом еще другие классы использовали

2021-08-03 07:46 UTC, DCrow commented
> Попроще вариант - fetchNextPage(): Future<Response>. Да, у сессии есть response и тут. Но зато сразу понятно, что к чему. Имхо)
Переиспользовать свойство response сесии как-то очень неочевидно.

Сам же противоречишь себе, что
> Мы же договорились не превращать мапкитовые ошибки в дартовые эксепшены. Так-то у future тоже есть onError.

Тогда надо их выдавать, иначе куда ошибку возвращать?

Со стримами @cream-cheeze тут описал проблему https://github.com/Unact/yandex_mapkit/pull/127#discussion_r679342503 что у нас race-condition, и если исправить ее, то может получится, что юзер подпишется на стрим, а ответ уже прошел и его юзер не получит.

> Переиспользовать свойство response сесии - совсем неочевидно, согласен. Но для меня так же неочевидно первый результат получать из сессии, а последующие напрямую от выполнения функций. Помимо следующей страницы может быть такая ситуация: вызвали searchByText, создалась и вернулась сессия, а при получении результата возникла ошибка - на этот случай есть метод retry - он тоже будет Future возвращать, несмотря на то, что это будет первая страница? Крайне запутанно.

Да получается не совсем очевидно, но из-за того, что у нативной сессии есть разные методы, приходится так изварачиваться. 
Либо вообще другой вариант это сделать чтобы сессия была отдельно стоящий класс. Юзер сам инициализирует объект сессии(на native стороне при этом сессии еще нет, пока не вызовут searchByText), и на нем может использовать searchByText/retry/fetchNextPage. 
Тогда каждый из методов возвращает Future с результатом. 
В этом случае получаем более очевидный интерфейс, пропадает проблема race-condition и не приходится усложнять интерфейс стримами. И в таком варианте можно все остальные(Suggest/Routing) держать. 

С ошибками похоже, что придется его в ответ запихивать, придется юзерам всегда проверять. Не нравится отбирать у пользователей возможность использовать await/async.

2021-08-03 08:58 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +    _streamController.sink.addError(arguments);
В смысле поле в Response, а не эксепшн в стрим

2021-08-03 09:01 UTC, ILAgent commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
Например, в сессию при создании передавать колбек. Она его будет дёргать при закрытии.

2021-08-03 09:04 UTC, ILAgent commented on lib/src/yandex_search_session.dart
> +class SearchSession {
Я написал зачем - для наглядности. Пользователь либы перейдёт в определение сессии, увидит контракт и поймёт, что она умеет.  А так увидит портянку из деталей реализации, которые ему не нужны. 
Если не класс, то хотя бы открытые члены вынести вверх.

2021-08-03 09:08 UTC, ILAgent commented
> > Мы же договорились не превращать мапкитовые ошибки в дартовые эксепшены. Так-то у future тоже есть onError.
> 
> Я может чего не знаю.. А в чём минусы? Удобно же - использовать для ошибок специально предусмотренный для этого механизм языка, благодаря чему можно не уродовать класс ответа.

Дело в том, что если мы можем не обработать ошибку future или стрима и получим крэш. Т.е. мы ответ мапкита превращаем в исключительную ситуацию (exception) - это не правильно. Апи мапкита же не роняет приложение, и мы не должны.

2021-08-03 09:10 UTC, ILAgent commented
>Помимо следующей страницы может быть такая ситуация: вызвали searchByText, создалась и вернулась сессия, а при получении результата возникла ошибка - на этот случай есть метод retry - он тоже будет Future возвращать, несмотря на то, что это будет первая страница? Крайне запутанно.

Да, плохой вариант. Всё-таки один стрим лучше.

2021-08-03 09:11 UTC, ILAgent commented
> >Мы же договорились не превращать мапкитовые ошибки в дартовые эксепшены. Так-то у future тоже есть onError.
> 
> Тогда надо их выдавать, иначе куда ошибку возвращать?

в Response, как договаривались

2021-08-03 09:13 UTC, ILAgent commented
> может получится, что юзер подпишется на стрим, а ответ уже прошел и его юзер не получит.

стрим должен хранит последний вариант и возвращать при подписке (как Future)

2021-08-03 09:16 UTC, ILAgent commented
>С ошибками похоже, что придется его в ответ запихивать, придется юзерам всегда проверять. 

Например, фильтровать стрим с помощью `where` )

2021-08-03 11:04 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +    _channel.setMethodCallHandler(_handleMethodCall);
Точно, согласен

2021-08-03 11:06 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
Как вариант

2021-08-03 11:39 UTC, cream-cheeze commented
Яснее не стало... Давайте сконцентрируемся на конкретных вещах, иначе ещё долго может здесь обсуждать. 

Сейчас есть такой интерфейс:

**YandexSearch**

- searchByText(String searchText, Geometry geometry, SearchOptions options): Future<SearchSession>

**SearchSession**

- Stream<SearchResponse> results  // стрим с результатами

- cancelSearch(): void
- retrySearch(): void
- fetchNextPage(): void
- closeSession():void
- resubmit(...) - может появиться в будущем

**SearchResponse**

- int found
- List<SearchItem> items
- int page
- bool hasNextPage

Вот пример кода, который сейчас работает:

```
var session = await YandexSearch.searchByText(
  searchText: query,
  geometry: Geometry.fromBoundingBox(
    BoundingBox(
      southWest: Point(latitude: 55.76996383933034, longitude: 37.57483142322235),
      northEast: Point(latitude: 55.785322774728414, longitude: 37.590924677311705),
    )
  ),
  searchOptions: SearchOptions(
    searchType: SearchType.geo,
    geometry: false,
  ),
);

_sessions[session.id] = session;

// Listen to results stream

StreamSubscription? subscription;

subscription = session.results.listen((res) {

  var resStr = res.toString();

  print('Page ${res.page}: $resStr');

  setState(() {
    responseByPages.add(res);
  });

  if (res.hasNextPage) {
    print('Got ${res.found} items, fetching next page...');
    session.fetchNextPage();
  } else {
    print('No more results available, closing session...');
    session.closeSession();
    _sessions.remove(session.id);
    subscription!.cancel();
  }

}, onError: (error) {

  if (error is PlatformException) {
    print('Error: ${error.message}');
  }

  subscription!.cancel();
});
}
```

Предлагаю @DCrow ещё раз оценить все приведённые выше аргументы и предложения, и написать, каким должен быть финальный интерфейс. И также переписать тот же самый пример под этот интерфейс - это поможет и тебе и нам, наглядно увидеть и убедиться, что там нет подводных камней.

Дальнейшее обсуждение, если ещё потребуется, будем вести только в таком формате - если кто-то не согласен, видит ошибку или проблему, то предлагает свой вариант какой-то части или всего интерфейса. Так, надеюсь, мы скорее придём к единогласному решению.

2021-08-03 15:13 UTC, ILAgent commented
Всё-таки посмотрел оригинальный интерфейс мапкита. Там так.
```
public interface SearchManager {
    @NonNull
    public Session submit(
        @NonNull String text,
        @NonNull Geometry geometry,
        @NonNull SearchOptions searchOptions,
        @NonNull SearchListener searchListener);

}

public interface Session {

    public static interface SearchListener {       
        public void onSearchResponse(@NonNull Response response);    
        public void onSearchError(@NonNull Error error);
    }

    public void cancel();
    
    public void retry(@NonNull SearchListener searchListener);

    public boolean hasNextPage();
    
    public void fetchNextPage(@NonNull SearchListener searchListener);

}
```

Т.е. в каждый метод передаётся отдельный колбек. Кажется правильно было бы сделать так же, только вместо приёма колбеков возвращать future. Получается как-то так.

```
class Response {
    List items;
    ...
}

class ResponeOrError {
    Response? response;
    String? error;
}

abstract class SearchSession {

    void cancel();
    
    Future<ResponseOrError> retry();

    boolean hasNextPage();
   
    Future<ResponseOrError> fetchNextPage();
}

class ResponseWithSession {
   Future<ResponseOrError> responseOrError;
   SearchSession session;
}


Future<ResponseWithSession> searchByText(...)
```

2021-08-03 15:23 UTC, DCrow commented
Я предлагаю следующий вариант(прототип)

search_session.dart
```dart
class SearchSession {
  late final MethodChannel _methodChannel;

  static const MethodChannel _systemChannel = MethodChannel('yandex_mapkit/yandex_search');

  static int _nextId = 0;

  static int _getNextId() => _nextId++;

  final int _id;

  int get id => _id;

  bool _active = true;

  bool get active => _active;

  SearchSession._(this._id) :
    _methodChannel = MethodChannel('yandex_mapkit/yandex_search_session_$_id');

  static Future<SearchSession> init() async {
    var id = SearchSession._getNextId();

    await _systemChannel.invokeMethod('initSearchSession', { 'id': id });

    return SearchSession._(id);
  }

  Future<SearchResponse> searchByText({
    required String searchText,
    required Geometry geometry,
    required SearchOptions searchOptions
  }) async {
    if (!active) throw('SearchSession has been closed');

    var params = {
      'searchText': searchText,
      'geometry': geometry.toJson(),
      'options': searchOptions.toJson(),
    };
    var result = await _methodChannel.invokeMethod('searchByText', params);

    return SearchResponse.fromJson(result['response']);
  }

  Future<void> cancelSearch() async {
    if (!active) throw('SearchSession has been closed');

    await _methodChannel.invokeMethod('cancelSearch');
  }

  Future<SearchResponse> retrySearch() async {
    if (!active) throw('SearchSession has been closed');

    var result = await _methodChannel.invokeMethod('retrySearch');

    return SearchResponse.fromJson(result['response']);
  }

  Future<SearchResponse> fetchNextPage() async {
    if (!active) throw('SearchSession has been closed');

    var result = await _methodChannel.invokeMethod('fetchNextPage');

    return SearchResponse.fromJson(result['response']);
  }

  Future<void> close() async {
    if (!active) throw('SearchSession has been closed');

    await _methodChannel.invokeMethod('close');
    await _systemChannel.invokeMethod('closeSearchSession', { 'id': id });

    _active = false;
  }
}
```

search_response.dart
```dart
class SearchResponse extends Equatable {

  final int                found;
  final String?            errorMsg;
  final List<SearchItem>   items;
  final int                page;
  final bool               hasNextPage;

  const SearchResponse({
    required this.found,
    required this.items,
    required this.page,
    required this.hasNextPage,
    this.errorMsg
  });

  factory SearchResponse.fromJson(Map<dynamic, dynamic> json) {
    List? items;

    if (json['errorMsg'] != null) {
      return SearchResponse(
        found: 0,
        items: [],
        page: 0,
        hasNextPage: false,
        errorMsg: json['errorMsg']
      );
    }

    if (json['items'] != null) {
      items = json['items'] as List?;
    }

    List<SearchItem>? mappedItems;

    if (items != null) {
      mappedItems = items.map((i) => SearchItem.fromJson(i)).toList();
    }

    return SearchResponse(
      found:        json['found'],
      items:        mappedItems ?? [],
      page:         json['page'],
      hasNextPage:  json['hasNextPage'],
    );
  }

  @override
  List<Object?> get props => <Object?>[
    found,
    items,
    page,
    hasNextPage,
    errorMsg
  ];

  @override
  bool get stringify => true;
}
```

search_example.dart (часть его)
```dart
void search(String query) async {

    print('Search query: $query');

    responseByPages.clear();

    var session = await SearchSession.init();

    _sessions[session.id] = session;

    var response = await session.searchByText(
      searchText: query,
      geometry: Geometry.fromBoundingBox(
        BoundingBox(
          southWest: Point(latitude: 55.76996383933034, longitude: 37.57483142322235),
          northEast: Point(latitude: 55.785322774728414, longitude: 37.590924677311705),
        )
      ),
      searchOptions: SearchOptions(
        searchType: SearchType.geo,
        geometry: false,
      ),
    );

    do {
      if (response.errorMsg != null) {
        print('Error: ${response.errorMsg}');
        await session.close();
        _sessions.remove(session.id);
        break;
      }

      var resStr = response.toString();

      print('Page ${response.page}: $resStr');

      setState(() {
        responseByPages.add(response);
      });

      if (!response.hasNextPage) {
        print('No more results available, closing session...');
        await session.close();
        _sessions.remove(session.id);
        break;
      }

      print('Got ${response.found} items, fetching next page...');
      await session.fetchNextPage();

    } while (response.hasNextPage);
  }
```

На мой взгляд тут получаем и возможность мульти-сессий, и используем один канал для каждой сессии, и можем получать последующие результаты вполне очевидным путем.

Какие моменты на мой взгляд решены
1. Нет усложнения работы с стримами(меньше кода, более ясная работа метода searchByText), ошибки заварачиваются в тот же ответ(в целом ошибка поиска это тоже вариант ответа).
2. Нет проблемы с калбэками для fetchNextPage, можно явно выдать результат и юзер что хочет, то и будет делать. 
3. race-condition в этом случае не будет, так как ответ сразу передастся 

Ошибка в данном случае в Response передается(можно и там усложнить, делать доп. класс где есть поля response и error, но мне кажется это каким-то излишеством)
Через нативные ошибки Future, не нравится так как, там может смешаться с ошибками `MethodChannel`, + в таком случае не возможно использовать await.

Если что-то упустил, просьба напомнить, а то диалог слишком большой все сразу вспомнить не могу...

2021-08-03 15:28 UTC, DCrow commented
> Т.е. в каждый метод передаётся отдельный колбек. Кажется правильно было бы сделать так же, только вместо приёма колбеков возвращать future. Получается как-то так.

В целом тоже считаю, что можно после каждого метода future с ответом возвращать. В своем примере я также возвращаю их(только не на столько усложненно, как у тебя)

2021-08-03 15:31 UTC, cream-cheeze commented
> await _systemChannel.invokeMethod('initSearchSession', { 'id': id });

Этот вызов что на стороне ios/android делает и возвращает?

2021-08-03 15:34 UTC, DCrow commented
> Этот вызов что на стороне ios/android делает и возвращает?

Создает объект YandexSearchSession(без самой сессии YMKSearchSession), который будет работать с каналом, id которого будет переданный в параметрах id.

2021-08-03 15:37 UTC, cream-cheeze commented
> > Этот вызов что на стороне ios/android делает и возвращает?
> 
> Создает объект YandexSearchSession(без самой сессии YMKSearchSession), который будет работать с каналом, id которого будет переданный в параметрах id.

На мой взгляд, это ошибка - так делать - ты создал объект сессии, которой по факту ещё нет. Можешь отправить ей команды, которые ни к чему не приведут.

2021-08-03 15:39 UTC, ILAgent commented
> > > Этот вызов что на стороне ios/android делает и возвращает?
> > 
> > 
> > Создает объект YandexSearchSession(без самой сессии YMKSearchSession), который будет работать с каналом, id которого будет переданный в параметрах id.
> 
> На мой взгляд, это ошибка - так делать - ты создал объект сессии, которой по факту ещё нет. Можешь отправить ей команды, которые ни к чему не приведут.

Мне тоже не очень нравится. Мапкит возвращает сессию при запросе, хорошо бы делать так же.

2021-08-03 15:39 UTC, DCrow commented
> На мой взгляд, это ошибка - так делать - ты создал объект сессии, которой по факту ещё нет. Можешь отправить ей команды, которые ни к чему не приведут.

Да такой момент есть, и в этом случае будет возвращаться ошибка в dart в `SearchResponse`.

2021-08-03 15:42 UTC, cream-cheeze commented
> Всё-таки посмотрел оригинальный интерфейс мапкита. Там так.
> 
> Т.е. в каждый метод передаётся отдельный колбек. Кажется правильно было бы сделать так же, только вместо приёма колбеков возвращать future. Получается как-то так.

Ну это, откровенно говоря, совсем не новость - я видел как там, иначе бы поиск не сделал. Пытался донести это не один раз до вас.

> class ResponseWithSession {
>    Future<ResponseOrError> responseOrError;
>    SearchSession session;
> }

Проблему возврата сессии и первого результата решает, но выглядит монструозно.

Никому не кажется, что мы просто зациклились на идее "сделать без колбэков", а колбэки здесь - самый естественный вариант?

searchByText - принял колбэк и вернул сессию, далее работа с сессией с передачей колбэка в каждый метод. По-моему максимально понятно. Уже и @ILAgent почти до этого же дошёл.

2021-08-03 15:48 UTC, cream-cheeze commented
Но если выбирать между вариантами @DCrow и @ILAgent  я бы выбрал последний - с ResponseWithSession - он хоть и нагромождает структуру ответа, но нет такой проблемы, как пустая сессия.

2021-08-03 15:50 UTC, ILAgent commented
> Проблему возврата сессии и первого результата решает, но выглядит монструозно.

Почему? По-моему сразу понятно, что к чему.

>Никому не кажется, что мы просто зациклились на идее "сделать без колбэков", а колбэки здесь - самый естественный вариант?
searchByText - принял колбэк и вернул сессию, далее работа с сессией с передачей колбэка в каждый метод. По-моему максимально понятно. Уже и @ILAgent почти до этого же дошёл.

Отчасти ты прав) Считаю, надо делать близкое к оригиналу апи. Заменить колбеки на фьючеры - получаем почти такое же, но более дартовое апи.

2021-08-03 15:52 UTC, ILAgent commented
Придумывать что-то новое и натягивать на оригинальное апи не стоит, т.к. это сложно в реализации и неудобно для пользователей, знакомых с мапкитом.

2021-08-03 15:53 UTC, DCrow commented
Если так не хочется создавать объект с не существующей сессией, то можно такой вариант.

search_result.dart
```dart
class SearchResult {
  SearchSession session;
  SearchResponse response;

  SearchResult({
    required this.session,
    required this.response
  });
}
```

yandex_search.dart (тут убрал suggest для наглядности)
```dart
class YandexSearch {

  static const MethodChannel _channel = MethodChannel('yandex_mapkit/yandex_search');

  static int _nextId = 0;

  static int _getNextId() => _nextId++;

  static Future<SearchResult> searchByText({
    required  String        searchText,
    required  Geometry      geometry,
    required  SearchOptions searchOptions
  }) async {

    var id = _getNextId();
    var params = {
      'id': id,
      'searchText': searchText,
      'geometry':   geometry.toJson(),
      'options':    searchOptions.toJson(),
    };
    var response = await _channel.invokeMethod('searchByText', params);

    return SearchResult(
      session: SearchSession(id),
      response: SearchResponse.fromJson(response['response'])
    );
  }
}
```

yandex_search.dart
```dart
part of yandex_mapkit;

class SearchSession {
  late final MethodChannel _methodChannel;

  final int _id;

  int get id => _id;

  bool _active = true;

  bool get active => _active;

  SearchSession(this._id) :
    _methodChannel = MethodChannel('yandex_mapkit/yandex_search_session_$_id');

  Future<void> cancelSearch() async {
    if (!active) throw('SearchSession has been closed');

    await _methodChannel.invokeMethod('cancelSearch');
  }

  Future<SearchResponse> retrySearch() async {
    if (!active) throw('SearchSession has been closed');

    var result = await _methodChannel.invokeMethod('retrySearch');

    return SearchResponse.fromJson(result['response']);
  }

  Future<SearchResponse> fetchNextPage() async {
    if (!active) throw('SearchSession has been closed');

    var result = await _methodChannel.invokeMethod('fetchNextPage');

    return SearchResponse.fromJson(result['response']);
  }

  Future<void> close() async {
    if (!active) throw('SearchSession has been closed');

    await _methodChannel.invokeMethod('close');

    _active = false;
  }
}
```

search_page.dart
```dart
void search(String query) async {

    print('Search query: $query');

    responseByPages.clear();

    var result = await YandexSearch.searchByText(
      searchText: query,
      geometry: Geometry.fromBoundingBox(
        BoundingBox(
          southWest: Point(latitude: 55.76996383933034, longitude: 37.57483142322235),
          northEast: Point(latitude: 55.785322774728414, longitude: 37.590924677311705),
        )
      ),
      searchOptions: SearchOptions(
        searchType: SearchType.geo,
        geometry: false,
      ),
    );

    var session = result.session;
    var response = result.response;

    _sessions[session.id] = session;

    do {
      if (response.errorMsg != null) {
        print('Error: ${response.errorMsg}');
        await session.close();
        _sessions.remove(session.id);
        break;
      }

      var resStr = response.toString();

      print('Page ${response.page}: $resStr');

      setState(() {
        responseByPages.add(response);
      });

      if (!response.hasNextPage) {
        print('No more results available, closing session...');
        await session.close();
        _sessions.remove(session.id);
        break;
      }

      print('Got ${response.found} items, fetching next page...');
      await session.fetchNextPage();

    } while (response.hasNextPage);
  }
```

В таком случае будет явно возвращаться результат с сессией, которая существует.

2021-08-03 15:59 UTC, DCrow commented
> Придумывать что-то новое и натягивать на оригинальное апи не стоит, т.к. это сложно в реализации и неудобно для пользователей, знакомых с мапкитом.

Не всегда, зависит от того на сколько сложное апи было. 
Например если у тебя для того чтобы получить данные надо 10 методов вызвать в одной последовательности, то лучше дать один метод юзеру, чем его тоже нагружать всем(часто во всяких нативные апи на C такое встречал)

В данном случае, не получается дать какой-то более удобный инструмент, чем то, что нам было дано в нативной либе, так что придется близко к нему и придерживаться...

2021-08-03 17:39 UTC, ILAgent commented
@DCrow твой вариант почти какой мой)
Я не стал использовать название SearchResult, т.к. имхо result, response - много терминов. 
hasNextPage - метод сессии в мапките, думаю стоит так и оставить. 
Если ошибка прям в респонзе , то все поля нулабельные, как-то некрасиво, т.к. их много. 

Но в целом вроде пришли к одному подходу)

2021-08-07 21:28 UTC, cream-cheeze commented on ios/Classes/YandexSearch.swift
> +  static var searchSessions: [Int:YandexSearchSession] = [:]
Сделал через колбэк

2021-08-07 21:42 UTC, cream-cheeze commented
Адаптировал свою последнюю имплементацию под интерфейс на фьючах, предложенный @ILAgent  и @DCrow, но 
с учётом [комментария](https://github.com/Unact/yandex_mapkit/pull/118#discussion_r684649912), оставленного мной в  соседнем PR– считаю, что так будет правильнее. 

+ пофиксил все оставшиеся замечания по этому ревью.

Android запилю позже – когда получу подтверждение, что всё устраивает.

2021-08-07 23:02 UTC, cream-cheeze commented
+ добавил searchByPoint - для поиска адреса по точке

2021-08-09 11:34 UTC, cream-cheeze commented
> Адаптировал свою последнюю имплементацию под интерфейс на фьючах, предложенный @ILAgent и @DCrow, но
> с учётом [комментария](https://github.com/Unact/yandex_mapkit/pull/118#discussion_r684649912), оставленного мной в соседнем PR– считаю, что так будет правильнее.
> 
> * пофиксил все оставшиеся замечания по этому ревью.
> 
> Android запилю позже – когда получу подтверждение, что всё устраивает.

Ладно, парни, не смотрите, если ещё не успели. @ILAgent вроде убедил, что не должно быть проблем с его реализацией в плане получения сессии - переделаю так же, тогда посмотрите.

2021-08-09 12:56 UTC, cream-cheeze commented
Всё, flutter+ios можно смотреть. @DCrow @ILAgent

2021-08-09 18:16 UTC, cream-cheeze commented
Android подъехал

2021-08-12 17:42 UTC, cream-cheeze commented
Добьём? Чуть-чуть осталось...

2021-08-12 19:47 UTC, ILAgent commented
извини, но туго со временем( постараюсь асап

2021-08-13 16:19 UTC, ILAgent commented on lib/src/types/search_response.dart
> +    required this.response,
почему required?

2021-08-13 16:19 UTC, ILAgent commented on lib/src/types/search_response.dart
> +  final int               page;
page в мапките нет, может не будем добавлять

2021-08-13 16:23 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +  final int               page;
Да, это отсебятина немножко, но удобно же, чтобы самому счет не вести. Нам это ничего не стоит. На полное соответствие с мэпкитом мы не претендуем, да и отличие не архитектурное. Я бы оставил.

2021-08-13 16:25 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Напрашивается отделение поиска от саджеста. Это на самом деле разные сущности. Давайте разнесём по разным классам.

2021-08-13 16:26 UTC, ILAgent commented on lib/src/yandex_search.dart
> +  static Future<SearchResponseWithSession> searchByText({
api в целом ок

2021-08-13 16:27 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +    required this.response,
Да, ошибка, похоже - поправлю.

2021-08-13 16:27 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Там @ILAgent уже в своей ветке с саджестом что-то делал. Лучше наверное уже не в этой ветке.

2021-08-13 16:29 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Да, я делал) Если разнести, будет меньше конфликтов. Саджест останется тут нетронутым тогда.

2021-08-13 16:31 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Так имя файла то наверное под плиск надо оставить - Search?

2021-08-13 16:37 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Да, переименуется сёрч в саджест, содержимое останется неизменённым

2021-08-13 16:37 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
> Да, я делал)

Я не заметил - думал это DCrow пишет )))

2021-08-13 16:37 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Да, переименуется сёрч в саджест, содержимое останется неизменённым

2021-08-13 16:56 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Я просто не понял, ты мне предлагаешь сделать рядом новый класс YandexSearchSuggestions и перенести в него все, что касается саджестов, или сделаешь это в своей ветке?

2021-08-13 21:28 UTC, cream-cheeze commented on lib/src/types/search_response.dart
> +    required this.response,
Вообще не то, чтобы ошибка - просто, видимо, хотел заставить указывать для наглядности оба поля, одно из них с нулевым значением. Убрал required, заменил assert'ом. Заодно реальную ошибку нашёл.

2021-08-14 13:32 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Предлагаю тебе) YandexSuggest достаточно имхо.

2021-08-14 13:33 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Точнее не перенести, а оставить как было, чтобы не было изменений, кроме названия в этих классах.

2021-08-16 15:04 UTC, DCrow requested changes

2021-08-16 15:04 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Тут на усмотрение @cream-cheeze

2021-08-16 15:05 UTC, DCrow commented on lib/src/types/search_response.dart
> +  final int               page;
Плохого ничего в параметре нет, пусть будет, удобный же.

2021-08-16 15:08 UTC, DCrow commented
> Ладно, парни, не смотрите, если ещё не успели. @ILAgent вроде убедил, что не должно быть проблем с его реализацией в плане получения сессии - переделаю так же, тогда посмотрите.

Да, там все выполняется по FIFO. [Тут](https://web.archive.org/web/20170704074724/https://webdev.dartlang.org/articles/performance/event-loop) можно почитать, не много устарело, но в целом хорошо рассказывает о том как выполняется код в дарте(включая async).

2021-08-17 12:43 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +	private class CloseSearchSessionCallback implements YandexSearchSessionCloseCallbackInterface {
Выше с @ILAgent обсуждали - он предложил через колбэк удалять сессию из списка (до этого было через вызов статического метода), с чем я согласился. Ну, конечно, в java пришлось погородить, так как, насколько я успел узнать, там не предусмотрена привычная работа с колбэками - только через интерфейсы. Как по мне - передача колбэка это более правильное решение, снижающее связанность кода.

2021-08-17 12:53 UTC, cream-cheeze commented on lib/src/yandex_search.dart
> +    final response = _channel.invokeMethod(
Вроде делал по аналогии с роутером в ветке @ILAgent. Насколько я знаю, любой метод, маркированный async должен возвращать Future - поэтому в сигнатуре метода указано Future<SearchResponseWithSession>. Фактически сразу вызвавший код получает в ответ SearchResponseWithSession, в котором сессия уже готова к использованию, а responseOrError подъедет, когда асинхронно выполнится then.

2021-08-17 14:46 UTC, DCrow commented on lib/src/yandex_search.dart
> +    final response = _channel.invokeMethod(
Может плохо выразился, мне тут просто интересно почему тут именно через then, хотя везде в других местах используешь async вариацию, вроде тут ничего не вынуждает использовать Future.

Пусть возвращает Future, чтоб было одинаково с роутером.
Там тоже увидел это, просто интересно стало, если ли на то какая-то везкая причина или просто

2021-08-17 14:48 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +	private class CloseSearchSessionCallback implements YandexSearchSessionCloseCallbackInterface {
Ок, пусть будет калбэк. 
В целом, мне кажется, думать про связанность в таком небольшом проекте рано.

2021-08-17 14:49 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +	private class CloseSearchSessionCallback implements YandexSearchSessionCloseCallbackInterface {
когда вырастет, будет поздно)

2021-08-17 15:11 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +	private class CloseSearchSessionCallback implements YandexSearchSessionCloseCallbackInterface {
Всегда есть верный друг рефактор)

2021-08-30 14:15 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Дошли руки снова, начал делать и понял, что в мэпките и за suggestions, и за search отвечает один SearchManager - точно решили разносить по классам? @DCrow  @ILAgent

2021-08-30 14:38 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +  SearchSession({required this.id}) :
Вот тут хочу обсудить сперва. Можно сделать свойство _isClosed, устанавливать его при вызове close() и проверять перед вызовом каждого метода, но что предполагается делать при вызове fetchNextPage и retrySearch, которые возвращают Future<SearchResponseOrError> - бросать эксепшн?

2021-08-30 14:44 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +    if (geometryOption == null) {
Перестраховался. Убрал лишние проверки.

2021-08-30 14:45 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchSession.java
> +    session = null;
Добавил

2021-08-30 14:45 UTC, cream-cheeze commented on ios/Classes/YandexSearchSession.swift
> +    session = nil
Добавил

2021-08-31 21:00 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Я бы таки разделил, а то слишком большой класс получается.

2021-09-01 13:56 UTC, DCrow commented on lib/src/yandex_search_session.dart
> +  SearchSession({required this.id}) :
Мне кажется лучше для всех методов(cancelSearch, retrySearch, hasNextPage, fetchNextPage, close), после того как был вызван close выкидывать ошибку через throw. 
Конечно, есть вариант возвращать всегда ошибку в SearchResponseOrError, но такое для close, hasNextPage, cancelSearch нельзя сделать.
Поэтому, кажется, что это самый оптимальный вариант.

2021-09-01 13:56 UTC, DCrow commented
Надо бы еще с мастером конфликты разрешить

2021-09-01 13:57 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Не настаиваю, но не против.

2021-09-01 14:01 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +  SearchSession({required this.id}) :
Ок, сделаю эксепшены

2021-09-01 14:02 UTC, cream-cheeze commented
Мастер подмержу в свою ветку

2021-09-01 18:35 UTC, cream-cheeze commented
@ILAgent, не подскажешь, в чём может быть проблема?

Почему-то не находит этот класс:
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;

/Developer/Projects/flutter/github/cream-cheeze/yandex_mapkit/android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java:13: error: cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  symbol:   class FlutterLifecycleAdapter
  location: package io.flutter.embedding.engine.plugins.lifecycle

2021-09-01 18:58 UTC, cream-cheeze commented
В общем запушил ветку со смеренным мастером, с разнесёнными suggest и search и всеми правками по ревью. Сумел проверить на iOS - всё ОК, на Android столкнулся с вышеуказанной проблемой - приложение не собирается, потому что ругается на отсутствие FlutterLifecycleAdapter.

2021-09-01 18:59 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +  SearchSession({required this.id}) :
Готово

2021-09-01 18:59 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchHandlerImpl.java
> +  private Map<Integer, SuggestSession>  		suggestSessionsById = new HashMap<>();
Готово

2021-09-01 19:14 UTC, cream-cheeze commented
> ![Screenshot 2021-09-01 at 21 37 09](https://user-images.githubusercontent.com/1291107/131725523-d16d8a10-5151-4fb4-88ad-2e53bd0fc84f.png)
> @ILAgent, не подскажешь, в чём может быть проблема?
> 
> Почему-то не находит этот класс:
> import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
> 
> /Developer/Projects/flutter/github/cream-cheeze/yandex_mapkit/android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java:13: error: cannot find symbol
> import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
> ^
> symbol: class FlutterLifecycleAdapter
> location: package io.flutter.embedding.engine.plugins.lifecycle
> 
> Это в твоей ветке появилось, и почему-то не находится у меня..

Всё, разобрался с этим.

2021-09-02 13:56 UTC, DCrow reviewed
Все хорошо, кроме мелочей, их поправить и мерджим

Про форматирование, чисто для читаемости, сейчас некоторые файлы трудно прочитать не отформатировав локально.

2021-09-02 13:56 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +  private YandexSearchHandlerImpl searchHandler;
А зачем мы эти переменные храним? Вроде же они нужны только при инициализации в setupChannels

2021-09-02 13:56 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchListener.java
> +public class YandexSearchListener implements Session.SearchListener {
Форматирование в файле(что-то с табами похоже) + Newline в конце файла

2021-09-02 13:56 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchSession.java
> +package com.unact.yandexmapkit;
Тут тоже с форматированием беда.

2021-09-02 13:56 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexSuggestHandlerImpl.java
> +}
NL

2021-09-02 13:56 UTC, DCrow commented on example/lib/examples/search_page.dart
> +    } on SearchSessionException catch (e) {
Что-то тут не понял, мы же в этом примере никогда ее не получим? 
Тут хочется продемонстрировать ситуации с ошибками? 
Не уверен что это хорошая идея, это же больше ближе к фатальным ошибкам. Тут к тому же получается, что это никогда не произойдет.

Да и к тому же в ReverseSearchPage такого нет, а там точно такая же сессия используется.

2021-09-02 13:56 UTC, DCrow commented on lib/src/yandex_search_session.dart
> +}
NL

2021-09-02 14:05 UTC, cream-cheeze commented on example/lib/examples/search_page.dart
> +    } on SearchSessionException catch (e) {
Ну вообще любой код, который может бросить эксепшн, стоит оборачивать в try catch. Необязательно уж настолько подробно примеры описывать - здесь видно наглядно, что методы могут бросить эксепшены и их нужно ловить. 
В ReverseSearchPage тоже нужно обернуть - просто забыл про этот пример.

2021-09-02 14:07 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +  private YandexSearchHandlerImpl searchHandler;
Я делал по аналогии с тем, что было - вопрос к предыдущему автору. В данной ситуации придерживаюсь политики "работает - не трогай". Могу удалить.

2021-09-02 14:08 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchListener.java
> +public class YandexSearchListener implements Session.SearchListener {
Возможно такое, обновлял студию, слетели настройки и часть файлов похерилась. Вроде правил, но, видимо, не все.

2021-09-02 14:13 UTC, DCrow commented on example/lib/examples/search_page.dart
> +    } on SearchSessionException catch (e) {
Да, что-то не подумал, что exception надо бы обернуть, тогда давай и в ReverseSearchPage добавим

2021-09-02 14:13 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +  private YandexSearchHandlerImpl searchHandler;
Давай уберем, раз решили разделять.

2021-09-02 15:12 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
> +  private YandexSearchHandlerImpl searchHandler;
Убрал

2021-09-02 15:13 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSearchSession.java
> +package com.unact.yandexmapkit;
Поправил

2021-09-02 15:14 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexSuggestHandlerImpl.java
> +}
Добавил

2021-09-02 15:14 UTC, cream-cheeze commented on example/lib/examples/search_page.dart
> +    } on SearchSessionException catch (e) {
Добавил

2021-09-02 15:16 UTC, cream-cheeze commented on lib/src/yandex_search_session.dart
> +}
Добавил

2021-09-02 15:28 UTC, merged

2021-09-02 15:29 UTC, DCrow commented
Теперь все супер
Смерджил в мастер

2021-09-02 17:22 UTC, cream-cheeze commented
@DCrow а у тебя на андроиде нормально собирается, если не пример запускать, а подключить плагин к проекту и запустить проект?

У меня ругается:

`E/flutter (10421): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: yandex_mapkit/yandex_map`

На iOS запускается нормально.

2021-09-02 17:35 UTC, DCrow commented
Конечно, для этого тестовое приложение и есть, проверить что все запускается.

Может у тебя используется Android embedding v1?

2021-09-02 17:39 UTC, cream-cheeze commented
> Конечно, для этого тестовое приложение и есть, проверить что все запускается.
> 
> Может у тебя используется Android embedding v1?

Я не про тестовое приложение как раз - тестовое у меня тоже запускается, а когда я попробовал свой проект собрать и запустить на андроиде, то получил эту ошибку. Можешь так же проверить - подключить последнюю версию плагина к другому проекту и запустить на андроиде?

2021-09-02 17:55 UTC, DCrow commented
В отдельном тоже работает.

Ты сделал как указано в README проекта? Там настроить файлы в папке android, ключи и тп.
У меня до того как это не сделал, выдавало эту ошибку.

2021-09-02 18:06 UTC, cream-cheeze commented
Перечитаю README. Раньше то я запускал, всё работало, но это было уже давно, т.к. я чаще на iOS запускаю. Но если у тебя работает, то хорошо - значит проблема локальная.

2021-09-02 18:51 UTC, cream-cheeze commented
Перепутано местами у меня было:

```
super.configureFlutterEngine(flutterEngine)
MapKitFactory.setApiKey("API_KEY")
```

а должно быть:

```
MapKitFactory.setApiKey("API_KEY")
super.configureFlutterEngine(flutterEngine)
```

Не понял, как это вышло, так как я определённо запускал приложение на андроиде, но главное, что разобрался. Спасибо, что отправил readme почитать, а то я бы ещё долго возился!