Driving route metadata added
Unact/yandex_mapkit pull request #139
Opened 2021-09-10 15:06 UTC by starikovvm

Добавил информацию о маршруте - расстояние и время в пути

2021-09-15 15:38 UTC, DCrow requested changes
Добрый вечер!

Спасибо за доработку! Только один момент возник, его поправить и можно мерджить.

2021-09-15 15:38 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +    private func localizedValueData(_ value: YMKLocalizedValue) -> [String: Any] {
Тут может nil прийти, который крешнит приложение. 
Надо поменять на `[String: Any?]` и также везде где используется метод

2021-09-16 08:09 UTC, starikovvm commented on ios/Classes/YandexDrivingRouter.swift
> +    private func localizedValueData(_ value: YMKLocalizedValue) -> [String: Any] {
поменял

2021-09-16 09:03 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +    private func localizedValueData(_ value: YMKLocalizedValue) -> [String: Any] {
Так выше все равно осталось `[String: Any]`. 
Теперь уже там вылетит

2021-09-16 09:36 UTC, starikovvm commented on ios/Classes/YandexDrivingRouter.swift
> +    private func localizedValueData(_ value: YMKLocalizedValue) -> [String: Any] {
там выше уже nil вернуться не может, localizedValueData возвращает не optional словарь.

2021-09-16 09:38 UTC, starikovvm commented on ios/Classes/YandexDrivingRouter.swift
> +    private func localizedValueData(_ value: YMKLocalizedValue) -> [String: Any] {
Можно поменять тип weight: [String: Any] на [String: [String: Any?]], но смысла особо в этом не вижу

2021-09-16 09:38 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +    private func localizedValueData(_ value: YMKLocalizedValue) -> [String: Any] {
Мы же только что поменяли localizedValueData, чтобы возвращал optional словарь

2021-09-16 09:40 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +    private func localizedValueData(_ value: YMKLocalizedValue) -> [String: Any] {
> Можно поменять тип weight: [String: Any] на [String: [String: Any?]], но смысла особо в этом не вижу

Да, такое как-то не очень, пусть остается как есть

2021-09-16 09:41 UTC, merged