Composite icons for placemarks
Unact/yandex_mapkit pull request #152
Opened 2021-10-09 22:21 UTC by cream-cheeze

Ответвился от мастера, перенёс в новую ветку свой ранее написанный код из ветки placemarks (саму placemarks пока не чистил - сделаю это, когда закончим с этим пулреквестом) с минимальными изменениями, связанными с проведённым в мастере рефакторингом. Для начала только iOS, чтобы время зря не тратить.

Ничего пока не стал менять - у тебя были вопросы по поводу стиля плейсмарков... Я всё ещё не вижу логики в том, что иконка - это атрибут стиля, считаю, что скорее наоборот, стиль - это атрибут иконки. В нативной библиотеки есть сущность Icon и IconStyle, что я и пытался повторить. Давай обсуждать за и против.

Пока переделывал, наткнулся на ошибку при удалении плейсмарков в мастере - поправил. Не понял, к чему были эти изменения, и зачем передавать весь объект плейсмарка при его удалении, если раньше передавался только id, и этого достаточно?

Также, я пока что закомментировал код в enableCameraTracking, требующий style в качестве аргумента. Во-первых, нужно сначала определиться с архитектурой, чтобы не переделывать по десять раз. А во-вторых, ты говорил, что готов переосмыслить эту фичу - предлагаю как раз здесь этим и заняться. Как уже говорил, данный функционал является частным случаем, и может быть легко реализован пользователями плагина самостоятельно - всё для этого имеется.

2021-10-19 12:37 UTC, cream-cheeze commented
> Так я не говорю, что у иконки не может быть стиля. Я говорю, что у плейсмарка есть стиль, у стиля есть набор иконок со своими стилями. Если дать пример, то вот так

Значит, я тебе сначала неправильно понял. Так я тоже не возражаю - доработаю.

> Ты же ее сам и добавил. В мастере id это строка, а ты в этом PR переопределил.

Сорян, похоже при отделении кода что-то лишнее хватанул.

> Закомменченный код потом надо будет убрать. Я в целом не против убрать сам стиль из этого метода, но не тут. Сейчас оно ничем не мешает, кроме того, что ты решил полностью изменить, то как плейсмарк создается. Если стиль оставить как он был и добавить только часть с композитными иконками внутрь него, то трогать это место и не придется.

Ок.

2021-10-20 11:01 UTC, DCrow commented
> Также, я пока что закомментировал код в enableCameraTracking, требующий style в качестве аргумента 

Вот тут убрал этот стиль #155, да и то что обсуждали насчет MapObjectCollection тоже добавил. В более удобной форме.

2021-10-20 11:03 UTC, cream-cheeze commented
> Вот тут убрал этот стиль #155, да и то что обсуждали насчет MapObjectCollection тоже добавил. В более удобной форме.

Да, видел ветку - отлично 👍

2021-11-01 12:34 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
А для чего вообще здесь equatable применительно к стилям используется?

2021-11-01 13:00 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Не вижу смысла в создании отдельного класса PlacemarkCompositeIcon, который что - будет содержать только дополнительное поле с называнием иконки? Это не решает проблему неуникальных названий - получается, что каждая иконка независима друг от друга, и проверить, что среди переданных иконок нет двух с одинаковым названием - сложно. Я тут немного встрял - нужно решить, как делать...

2021-11-01 13:29 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Можно, конечно, ещё схитрить и использовать в качестве имени иконки её индекс в массиве... Так вообще можно скрыть от пользователя плагина работу с именами. Не знаю, хорошо это или плохо...

2021-11-01 14:29 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
equatable для Placemark нужен, стиль же только в нем используется.
Так никогда не будут корректно сравняться два одинаковых Placemark(при этом и другие методы, которые полагаются на равенство Placemark начинают ломаться)

Не понял почему не решает, в документации указать, что нельзя указывать, а при инициализации класса дубликаты убирать. Так собственно MapObjectCollection/ClusterizedPlacemarkCollection работают. Они не дают добавлять объекты с одинаковыми mapId более одного раза.

Насчет индекса трудно сказать, вполне вероятно, что есть случаи, когда надо давать юзеру возможность менять название. Тут считаю лучше дать возможность, чтобы потом не ломать ничего при переделывании.

2021-11-01 14:35 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
> Не понял почему не решает, в документации указать, что нельзя указывать, а при инициализации класса дубликаты убирать. Так собственно MapObjectCollection/ClusterizedPlacemarkCollection работают. Они не дают добавлять объекты с одинаковыми mapId более одного раза.

Потому что костыль получается - если нужно в документации писать то, чего делать нельзя, не запрещая это делать в явном виде. Типа: вы, конечно, можете передать две иконки с одинаковым именем, но одна у вас не отобразиться. Могу сделать так, если хочешь, но я бы сам так не стал делать.

2021-11-01 14:47 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Все же я бы не называл это костылем. Это скорее предупреждение, что если укажите два одинаковых названия, не обязательно будет работать, так как вы ожидаете.

Вообще, что заставляет делать эту проверку? Карта падает, если указать два одинаковых названия?

2021-11-01 14:51 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Не проверял, но судя по документации просто перезапишется последним (creates o resets):

> Creates or resets a named layer with an icon and its style.

Что заставляет - нежелание ставить пользователя в ситуацию, когда код не работает так как ожидается, а в чём причина - можно не понять. Плюс лишние вопросы на гитхабе.

2021-11-01 14:54 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Так если не мешает, то пусть работает как в нативной либе.
Вопросы всегда бывают, а тут это вообще нативная фича...

2021-11-01 14:57 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Ну ок. Т.е. добавляем необязательный атрибут name в PlacemarkIcon и заменяем map на list?

2021-11-01 15:01 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
В случае, если используется composite, а в одной или нескольких из переданных иконок нет имени: бросаем эксепшн?

2021-11-01 15:02 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Давай так, если ты новый класс не хочешь делать. 
Единственное, это при инициализации, надо list дублировать, чтобы его из вне не могли изменить.

2021-11-01 15:03 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
> В случае, если используется composite, а в одной или нескольких из переданных иконок нет имени: бросаем эксепшн?

В таком случае лучше отдельный класс, чем меньше exception, тем лучше

2021-11-01 15:12 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Вообщем получаем либо
1. Используем текущий класс PlacemarkIcon, и там проверяем через assert.
2. Делаем новый класс, где проверка не нужна.

На мой взгляд новый класс лучше, так как сразу говорит что нужно.

2021-11-01 19:09 UTC, cream-cheeze commented on lib/src/types/rect.dart
> +}
Поправил

2021-11-01 19:09 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  PlacemarkIcon.fromIconName({required String iconName, PlacemarkIconStyle? style}) :
Готово

2021-11-01 19:10 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  PlacemarkIcon({
Готово

2021-11-01 19:10 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final Map<String,PlacemarkIcon>?  compositeIcon;
Сделал отдельный класс

2021-11-01 19:10 UTC, cream-cheeze commented on lib/src/types/map_objects/map_object.dart
> +  final bool isVisible;
Выпилил

2021-11-01 19:11 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +        json['icon']['iconName'] = icon!.iconName!;
Ещё проще упростил

2021-11-01 19:11 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +        'min': {
Добавил

2021-11-01 19:11 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  List<Object> get props {
Готово

2021-11-01 19:12 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  }) : assert((icon != null || compositeIcon != null), 'Either icon or compositeIcon must be provided');
Убрал проверку. Если указаны обе - в комментарии написано, что приоритет за icon.

2021-11-01 19:12 UTC, cream-cheeze commented on example/lib/examples/reverse_search_page.dart
> +                      //style: const PlacemarkStyle(iconName: 'lib/assets/place.png', opacity: 0.5, scale: 0.75)
Раскоментил

2021-11-01 19:12 UTC, cream-cheeze commented on example/lib/examples/placemark_page.dart
> +    onTap: (Placemark self, Point point) => print('Tapped me at ${point.latitude},${point.longitude}'),
Вернул

2021-11-01 19:13 UTC, cream-cheeze commented on example/lib/examples/camera_tracking_page.dart
> +                          // style: const PlacemarkStyle(iconName: 'lib/assets/place.png', opacity: 0.5),
Убрал

2021-11-01 19:13 UTC, cream-cheeze commented on ios/Classes/YandexMapController.swift
> +    placemark.isVisible = (params["isVisible"] as! NSNumber).boolValue
Убрал

2021-11-01 19:13 UTC, cream-cheeze commented on ios/Classes/YandexMapController.swift
> +        if let iconStyle = icon["style"] as? [String: Any] {
Готово

2021-11-01 19:14 UTC, cream-cheeze commented on ios/Classes/YandexMapController.swift
> +        guard let img = getIconImage(icon) else {
Убрал проверку

2021-11-01 19:19 UTC, cream-cheeze commented
Капец там опять конфликтов вылезло...

2021-11-02 09:29 UTC, cream-cheeze commented
> Капец там опять конфликтов вылезло...

Смержил, конфликты разрешил, вроде норм. Можно смотреть.

Правда в ходе тестирования на андроид заметил некоторые косяки в примерах не связанных с плейсмарками - переключился на мастер, чтобы проверить - там воспроизводится:

1. Построение маршрута лагает очень сильно - интерфейс зависает на несколько секунд в примере, даже прелоадер перестаёт крутиться.
2. В Layers example по кнопке Show user layer иконка то появляется, то нет, иногда секунд через 5-10 сама, иногда после повторного нажатия. Get user point периодически выдаёт ошибку (как раз в момент, когда иконки нет на карте):
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
    Receiver: null
    Tried calling: []("point")
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
    #1      YandexMapController.getUserTargetPoint (package:yandex_mapkit/src/yandex_map_controller.dart:216:15)
    <asynchronous suspension>
    #2      _LayersExampleState.build.<anonymous closure> (package:yandex_mapkit_example/examples/layers_page.dart:80:33)
    <asynchronous suspension>
```
3. Search выдаёт ошибку, прелоадер продолжает крутиться:
```
E/MethodChannel#yandex_mapkit/yandex_search: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.unact.yandexmapkit.YandexSearch.searchByText(YandexSearch.java:64)
        at com.unact.yandexmapkit.YandexSearch.onMethodCall(YandexSearch.java:42)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.unact.yandexmapkit.YandexSearch.searchByText(YandexSearch.java:64)
        at com.unact.yandexmapkit.YandexSearch.onMethodCall(YandexSearch.java:42)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    )
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.unact.yandexmapkit.YandexSearch.searchByText(YandexSearch.java:64)
        at com.unact.yandexmapkit.YandexSearch.onMethodCall(YandexSearch.java:42)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    )
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
```

2021-11-02 09:54 UTC, cream-cheeze commented
И ещё с кластерами что-то не так в моей ветке - пример не работает как должно, пока не понял почему. В мастере работает и на iOS в моей ветке тоже работает... Вроде я кластерный контроллер вообще не трогал.

2021-11-02 10:36 UTC, DCrow requested changes

2021-11-02 10:36 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +enum RotationType {
Это надо бы либо в самый вверх либо в самый низ. 
Теряется среди классов

2021-11-02 10:36 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  PlacemarkIcon._({
А где это используется?

2021-11-02 10:36 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  Map<String, dynamic> toJson() {
Тут же тоже можно проще написать?

2021-11-02 10:36 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  List<Object?> get props {
А почему не просто?

```dart
@override
  List<Object?> get props => <Object?>[
    anchor,
    rotationType,
    zIndex,
    flat,
    visible,
    scale,
    tappableArea,
  ];
```

2021-11-02 10:36 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +}
Новой строки не хватает

2021-11-02 10:36 UTC, DCrow commented on lib/src/types/rect.dart
> +class Rect {
Давай его назовем MapRect, чтобы он не совпадал с Rect из основной либы флаттера. 
При возможности лучше все же избегать совпадений с флаттером.

2021-11-02 10:36 UTC, DCrow commented on ios/Classes/YandexPlacemarkController.swift
> +      if let iconStyle = icon["style"] as? [String: Any] {
Так стиль же всегда есть?

2021-11-02 10:36 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +
Тут надо убрать изменение

2021-11-02 10:36 UTC, DCrow commented on example/lib/examples/placemark_page.dart
> +                Row(
Давай в этом примере еще и update добавим, по аналогии с другими 2 точками

2021-11-02 10:36 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +import com.yandex.mapkit.map.Rect;
Тут тоже надо изменения убрать

2021-11-02 10:36 UTC, DCrow commented on lib/src/types/map_objects/placemark.dart
> +  final List<PlacemarkCompositeIcon>? compositeIcon;
А что будет если отдадим пустой список?

2021-11-02 10:36 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +    placemark.setUserData(params.get("id"));
Это надо убрать, оно только при инциализации должно задаваться

2021-11-02 10:36 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +      if (tappableAreaMin != null && tappableAreaMax != null) {
Разве бывают ситуации, когда одно есть, а другого нет?

2021-11-02 10:36 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +    if (params.get("zIndex") != null) {
У нас же такого не бывает, он всегда не null

2021-11-02 10:36 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +    if (params.get("zIndex") != null) {
Также вроде это с 82 строчкой пересекается же? 
Отсюда тогда надо убрать

2021-11-02 10:43 UTC, DCrow commented
> Построение маршрута лагает очень сильно - интерфейс зависает на несколько секунд в примере, даже прелоадер перестаёт крутиться.

Оно и раньше так было. Объем данных очень большой.

> В Layers example по кнопке Show user layer иконка то появляется, то нет, иногда секунд через 5-10 сама, иногда после повторного нажатия. Get user point периодически выдаёт ошибку (как раз в момент, когда иконки нет на карте):

Про ошибку знаю, а вот насчет появления это от нативной либы зависит, она не всегда может сразу получить местоположение.

> Search выдаёт ошибку, прелоадер продолжает крутиться

Надо будет поправить

> И ещё с кластерами что-то не так в моей ветке - пример не работает как должно, пока не понял почему. В мастере работает и на iOS в моей ветке тоже работает... Вроде я кластерный контроллер вообще не трогал.

У тебя не работает из-за [этого](https://github.com/Unact/yandex_mapkit/pull/152/files#diff-87ede9c27d373c46d3040c17c4f569f01edba725e8ab05c27947061e80ad1e03R102). Ты обнуляешь id, и при поиске возвращаются одни null, из-за чего дальше ничего не вызывается.

2021-11-02 10:50 UTC, cream-cheeze commented
> У тебя не работает из-за [этого](https://github.com/Unact/yandex_mapkit/pull/152/files#diff-87ede9c27d373c46d3040c17c4f569f01edba725e8ab05c27947061e80ad1e03R102). Ты обнуляешь id, и при поиске возвращаются одни null, из-за чего дальше ничего не вызывается.

Точно, заработало, спасибо.

2021-11-02 10:52 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +    placemark.setUserData(params.get("id"));
Поправил

2021-11-02 10:54 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +      if (tappableAreaMin != null && tappableAreaMax != null) {
Ну не бывают. Наверное и не бывает когда обоих нет. Ранее объяснял уже логику своих проверок. Этот код был написан давно, и сейчас при переносе я его не стал переосмысливать полностью с учётом знания твоих предпочтений - просто перенёс в отдельную ветку и смерил с мастером.

2021-11-02 10:57 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  PlacemarkIcon._({
Ты в прошлый раз зачем-то просил приватным конструктор сделать - я сделал. Его вообще можно убрать, получается.

2021-11-02 11:21 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  final List<PlacemarkCompositeIcon>? compositeIcon;
Да ничего не будет - то же самое, что и null передать.

2021-11-02 11:37 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  Map<String, dynamic> toJson() {
Можно, указал попроще

2021-11-02 11:37 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +enum RotationType {
Перенёс

2021-11-02 11:37 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  PlacemarkIcon._({
Удалил

2021-11-02 11:37 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  Map<String, dynamic> toJson() {
Можно, написал

2021-11-02 11:40 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +  List<Object?> get props {
Если реально интересно, то в прошлом ревью tappableArea проверялся на null. Ты попросил переделать на Object? - я переделал, проверка ушла, но var props остался из прошлой реализации. 

Слушай, ну такие мелочи, если настолько раздражают, не проще ли тебе самому перед мержем поправить? Делов то... Код может быть написан тысячами способов. Куча времени уходит на этот "футбол". Понятно, что твоя репа, и тебе хочется чтобы всё было по-твоему - ради бога, но не мучай контрибьютеров уж настолько, пожалуйста...

Поменял.

2021-11-02 11:40 UTC, cream-cheeze commented on lib/src/types/map_objects/placemark.dart
> +}
Добавил

2021-11-02 11:40 UTC, cream-cheeze commented on lib/src/types/rect.dart
> +class Rect {
Переименовал

2021-11-02 11:40 UTC, cream-cheeze commented on ios/Classes/YandexPlacemarkController.swift
> +      if let iconStyle = icon["style"] as? [String: Any] {
Убрал проверку

2021-11-02 11:40 UTC, cream-cheeze commented on ios/Classes/YandexMapController.swift
> +
Убрал

2021-11-02 11:40 UTC, cream-cheeze commented on example/lib/examples/placemark_page.dart
> +                Row(
Добавил

2021-11-02 11:40 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +import com.yandex.mapkit.map.Rect;
Убрал

2021-11-02 11:41 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +      if (tappableAreaMin != null && tappableAreaMax != null) {
Убрал проверку

2021-11-02 11:41 UTC, cream-cheeze commented on android/src/main/java/com/unact/yandexmapkit/YandexPlacemarkController.java
> +    if (params.get("zIndex") != null) {
Да, это лишнее - здесь косяк был, убрал

2021-11-03 14:38 UTC, DCrow reviewed
Вроде все норм, осталось только убрать изменения в YandexMapController для iOS и Android и можно мерджить

2021-11-03 14:38 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +
Так это тоже надо убрать и ниже тоже

2021-11-03 14:38 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +
Так это не убралось же?

2021-11-03 17:19 UTC, cream-cheeze commented on ios/Classes/YandexMapController.swift
> +
Так ты про что? Я думал, ты про таб в начале пустой строки - я его удалил.

2021-11-04 07:24 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +
Так я вообще об изменениях в файле. 
Через гит же видно, что в файле есть какие-то изменения(новые строки, табы и тп). 
Их же не должно быть.

2021-11-04 09:25 UTC, cream-cheeze commented on ios/Classes/YandexMapController.swift
> +
Ты коммиты смотришь или итоговый файл? Понятно, что по коммитам ты видишь изменения в этом файле - я же мержил мастер в свою ветку, и там была целая куча конфликтов, которые пришлось разрешать, но в итоге сейчас если сравнишь ios/Classes/YandexMapController.swift и android/src/main/java/com/unact/yandexmapkit/YandexMapController.java в master и composite_icons, то не увидишь разницы - они не отличаются.

2021-11-08 07:46 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +
С этим файлом извиняюсь ошибка произошла. А в YandexMapController.java изменения есть.

2021-11-08 08:28 UTC, cream-cheeze commented on ios/Classes/YandexMapController.swift
> +
Слушай, ну я получил diff master и своей ветке, и всё, что там видно:

- 216 строка - tab в начале строки (удалил)
- 518 строка - tab в начале строки (удалил)
- пустая строка в конце файла - в master нет, у меня есть (т.е. в моей ветке верно)

Всё. Ты что-то ещё видишь?

2021-11-08 08:40 UTC, merged

2021-11-08 08:40 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +
Теперь все хорошо