toggleMapRotation; Placemark direction & rotationType
Unact/yandex_mapkit pull request #68
Opened 2020-11-01 21:52 UTC by ryufitreet

https://github.com/Unact/yandex_mapkit/issues/67

2020-11-09 08:44 UTC, DCrow requested changes

2020-11-09 08:44 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +    placemark.setDirection(((Double) params.get("opacity")).floatValue());
Думаю тут описка, и должен быть параметр `direction`?

2020-11-09 08:44 UTC, DCrow commented on lib/src/types/placemark.dart
> +  final String rotationType;
Не совсем понятно почему для rotationType был выбран тип String

Лучше либо сделать как отдельный класс с константами(так как в dart нельзя создавать enum с заданными значениями), либо же сделать это `final bool noRotation`

2020-11-09 08:44 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +    if !(params["direction"] is NSNull) {
В Swift правильней писать `if !(params["direction"] != nil)`

2020-11-09 08:44 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +
Лишние пробелы

2020-11-09 08:44 UTC, DCrow commented on example/lib/main.dart
> +  const RotatePage(),
Для названия лучше использовать существительные, т.е. тут `RotationPage`

2020-11-09 08:44 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +
Лишние пробелы

2020-11-09 08:44 UTC, DCrow commented on example/lib/examples/rotate_page.dart
> +
Лишние пробелы

2020-11-09 08:46 UTC, DCrow commented
Спасибо за PR!

Оставил замечания по найденным моментам

2020-11-12 14:14 UTC, DCrow reviewed
Все хорошо, кроме лишних пробелов в форматировании

2020-11-12 14:14 UTC, DCrow commented on example/lib/examples/rotation_page.dart
> +
Лишний пробел

2020-11-16 18:32 UTC, ryufitreet commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +
Сорян, не заметил. Поправил.

2020-11-17 08:10 UTC, merged