driving route support
Unact/yandex_mapkit pull request #74
Opened 2020-12-04 16:38 UTC by worldofsites

2020-12-07 06:39 UTC, worldofsites commented
@DCrow added driving route support (both Android and iOS):
![](https://i.imgur.com/KsffG1d.gif)

2020-12-07 08:48 UTC, DCrow requested changes
Спасибо за PR!

Оставил замечания по PR

2020-12-07 08:48 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +    if (placemarkParams.count > 0){
Не могу понять, почему у нас точка разделана на placemark и point в параметрах?
Для чего это сделано?

Кроме того тут явно смешиваются обычные Placemark, которые добавляются через addPlacemark и PLACEMARK_CURRENT_LOCATION. 
Правильней будет выделить его в отдельную переменную для этого процесса(вместо использования `userData`), а логику добавления точки на карту вынести в отдельный метод.

2020-12-07 08:48 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +    if (drivingSession != nil) {
Эта проверка же, внутри `cancelRoute` есть?

2020-12-07 08:48 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +    setDrivingSession()
Надо бы назначение drivingFromLocation, drivingToLocation, drivingPolyline подвинуть сюда, либо использовать их как входные параметры, чтобы было понятно для чего они вообще используются(им назначаются значения) в методе.

2020-12-07 08:48 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +          methodChannel.invokeMethod("onDrivingRoutes", arguments: arguments)
А почему не в конце метода, после того как на карте отобразились линии?

2020-12-07 08:48 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +import YandexMapKitDirections
Также по файлу в целом, форматирование в некоторых новых методах надо поправить

2020-12-07 08:48 UTC, DCrow commented on example/lib/main.dart
> +}
Новую строку надо вернуть

2020-12-07 08:48 UTC, DCrow commented on example/lib/examples/routing_page.dart
> +                          pointTo: const Point(
Стоит это сделать переменной, чтобы было по аналогии с другими примерами.

2020-12-07 08:48 UTC, DCrow commented on example/lib/examples/routing_page.dart
> +                      _showMessage(context,
Что-то форматирование страдает, выше считай такое же выражение, а формат другой... 
Надо бы одного формата придерживаться

2020-12-07 08:48 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +  private static final boolean USE_IN_BACKGROUND = false;
Возникает вопрос, почему на Swift не выносили в константы?

2020-12-07 08:48 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +    drivingPolyline.outlineColor = outlineColorLong.intValue();
Надо бы сделано аналогично Swift части

2020-12-07 08:48 UTC, DCrow commented on lib/src/types/polyline.dart
> +    this.coordinates,
Вместо убирания `@required`, можно передавать []. 
В целом не нравится идея убирания обязательности, в будущем приведет к ошибкам

2020-12-07 08:48 UTC, DCrow commented on ios/yandex_mapkit.podspec
> +  s.dependency 'YandexMapKitSearch', '3.5.0'
Тут же ничего не менялось?

2020-12-07 16:22 UTC, worldofsites commented on lib/src/yandex_map_controller.dart
> +  LocationStatusUpdatedCallback _locationStatusUpdatedCallback;
Событие onLocationStatusUpdated возникает в случае, когда изменилось состояние определения текущей локации пользователя на notAvailable. В примере не используется, но, возможно, кому-то может понадобиться. Если в этом нет необходимости, то ок, уберу.

2020-12-07 16:22 UTC, worldofsites commented on ios/Classes/YandexMapController.swift
> +    if (placemarkParams.count > 0){
Placemark - содержит информацию о стилизации точки, отображающей текущее местоположение пользователя.
Point - это координата места назначения.

Для решения задачи нужно знать:
Координату места назначения
Стиль линии (polyline)
Маркер текущей позиции пользователя (placemark)

Добавил наследование от PlacemarkStyle и PolylineStyle, чтобы уйти от координат.
Передаю в метод routeToLocation параметры destination, polylineStyle, placemarkStyle.

Убрал использование placemarks и PLACEMARK_CURRENT_LOCATION. Завел отдельный drivingStartingPlacemark.

+ рефакторинг по выносу логики подготовки точек в метод preparePlacemark

2020-12-07 16:22 UTC, worldofsites commented on ios/Classes/YandexMapController.swift
> +    if (drivingSession != nil) {
+

2020-12-07 16:22 UTC, worldofsites commented on ios/Classes/YandexMapController.swift
> +    setDrivingSession()
Полям drivingFromLocation, drivingToLocation присваиваются значения сразу после обработки аргументов метода. Используются не только в YandexMapController, но и при изменении локации пользователя в событии onLocationUpdated.

2020-12-07 16:22 UTC, worldofsites commented on ios/Classes/YandexMapController.swift
> +          methodChannel.invokeMethod("onDrivingRoutes", arguments: arguments)
+

2020-12-07 16:22 UTC, worldofsites commented on ios/Classes/YandexMapController.swift
> +import YandexMapKitDirections
Есть какая-то конфигурация по форматам?

2020-12-07 16:22 UTC, worldofsites commented on example/lib/main.dart
> +}
Форматирование main.dart откатил.

2020-12-07 16:22 UTC, worldofsites commented on example/lib/examples/routing_page.dart
> +                          pointTo: const Point(
+

2020-12-07 16:22 UTC, worldofsites commented on example/lib/examples/routing_page.dart
> +                      _showMessage(context,
Есть какая-то конфигурация по форматам?

2020-12-07 16:23 UTC, worldofsites commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +  private static final boolean USE_IN_BACKGROUND = false;
+

2020-12-07 16:23 UTC, worldofsites commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +    drivingPolyline.outlineColor = outlineColorLong.intValue();
Было сделано как и в имеющемся ранее методе addPolyline.

2020-12-07 16:23 UTC, worldofsites commented on lib/src/types/polyline.dart
> +    this.coordinates,
Откатил.
[] тоже может привести к ошибкам.

2020-12-07 16:23 UTC, worldofsites commented on ios/yandex_mapkit.podspec
> +  s.dependency 'YandexMapKitSearch', '3.5.0'
+

2020-12-10 14:19 UTC, DCrow requested changes
Оставил еще замечания, по поводу новых изменений

2020-12-10 14:19 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +  private static let DESIRED_ACCURACY: Double = 0
Насколько я понимаю, в swift рекомендуемая нотация для констант это camelCase

2020-12-10 14:19 UTC, DCrow commented on example/lib/examples/routing_page.dart
> +                      _showMessage(context,
В проекте какая-то определенная не стоит. Просто когда читаешь, сразу в глаза падает эта странность

2020-12-10 14:19 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +import YandexMapKitDirections
На будущее надо будет в проекте гайдлайны указать.

А так придерживаться рекомендуемых code-style для соответствующих языков.
Например для [Swift](https://google.github.io/swift/)

2020-12-10 14:19 UTC, DCrow commented on lib/src/yandex_map_controller.dart
> +  LocationStatusUpdatedCallback _locationStatusUpdatedCallback;
Я о тому что, код должен иметь какое-то назначение, если его использовать нельзя, то это получается бесполезный код, который только мешает.

В данном случае можно дать возможность в методе `routeToLocation` передавать callback

2020-12-10 14:19 UTC, DCrow commented on ios/Classes/YandexMapController.swift
> +    if (startingPointStyle.count > 0){
Более предпочтительно использовать такого рода проверку `!startingPointStyle.isEmpty`

2020-12-10 14:19 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +  private YandexMapPolylineStyle drivingPolylineStyle;
Тут тоже возникает вопрос, почему здесь вынесено в отдельный класс, а в Swift нет?
(На мой взгляд в Swift более ясно выглядит)

2021-01-13 11:16 UTC, DCrow commented
There are a lot of conflicts with the current project. 
Firstly they need to be fixed.

Also styling has been moved to separate classed which can be used here.

In my opinion it's better to fix all of those issues in a separate PR, along with issues left from this PR.

2021-01-13 11:16 UTC, closed without merging