Create get visible region method
Unact/yandex_mapkit pull request #83
Opened 2021-01-14 12:09 UTC by TatianaBelova

For expansion of functionality.

2021-01-15 10:19 UTC, DCrow requested changes
Спасибо за PR!

Оставил замечания. Также нужна реализация для iOS стороны

2021-01-15 10:19 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +    arguments.put("bottomLeft", new HashMap<String, Double>() {{
Лучше параметрам также добавить point в название, чтобы бы аналогично другим передаваемым параметрам(см `southWestPoint` в `setBounds`)

2021-01-15 13:50 UTC, TatianaBelova commented on android/src/main/java/com/unact/yandexmapkit/YandexMapController.java
> +    arguments.put("bottomLeft", new HashMap<String, Double>() {{
Готово

2021-01-15 14:32 UTC, DCrow commented
Извиняюсь, с первого раза не заметил.

Еще не хватает примера в тестовом приложении, чтобы можно было посмотреть, что добавляемый функционал работает, и чтобы другие разработчики могли увидеть, как пользоваться новым методов.

В остальном все хорошо

2021-02-15 07:02 UTC, TatianaBelova commented
> Извиняюсь, с первого раза не заметил.
> 
> Еще не хватает примера в тестовом приложении, чтобы можно было посмотреть, что добавляемый функционал работает, и чтобы другие разработчики могли увидеть, как пользоваться новым методов.
> 
> В остальном все хорошо

Добавила)

2021-02-16 08:12 UTC, DCrow commented
Теперь перестало собираться тестовое приложение. Выдает следующую ошибку
```
Xcode's output:
↳
    lib/examples/map_controls_page.dart:168:27: Error: The getter 'ScaffoldMessenger' isn't defined for the class '_MapControlsExampleState'.
     - '_MapControlsExampleState' is from 'package:yandex_mapkit_example/examples/map_controls_page.dart' ('lib/examples/map_controls_page.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
                              ScaffoldMessenger.of(context).showSnackBar(
```

В примерах нигде SnackBar не используется, обычно все `print` в консоль выводится. 
Надо бы тут также сделать.

2021-02-17 08:39 UTC, TatianaBelova commented
> Теперь перестало собираться тестовое приложение. 
> В примерах нигде SnackBar не используется, обычно все `print` в консоль выводится.
> Надо бы тут также сделать.

Пару дней назад обновила флаттер и тестовое собиралось, но заменила на print.

2021-02-18 11:12 UTC, DCrow commented
Видимо, синтаксис только для нового флаттера работал, а этот проект должен поддерживать и более старые версия флаттера.

Сейчас все хорошо! Спасибо!

2021-02-18 11:12 UTC, merged