Implemented basic driving router
Unact/yandex_mapkit pull request #90
Opened 2021-03-11 19:36 UTC by ILAgent

Linked to #34
Building routes polylines according to input way points and via points/

2021-04-01 10:16 UTC, DCrow requested changes
Спасибо за доработку!

Оставил замечания. 
Также надо исправить все предупреждения линтера и форматирование поправить, по аналогии с другими файлами соответствующих языков.

2021-04-01 10:16 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +        session = router!.requestRoutes(with: requestPoints, drivingOptions: drivingOptions, vehicleOptions: vehicleOptions) { (routes, error) in
Тут такая же ситуация как для java стороны. 
Надо использовать отдельный handler, который уже будет вызывать методы на dart стороне, а не дожидаться ответа сразу при запросе из dart стороны.

2021-04-01 10:16 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +        router = router ?? YMKDirections.sharedInstance().createDrivingRouter()
Стоит сразу в конструкторе класса установить `router`, и потом им всегда пользоваться.

2021-04-01 10:16 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +    private var session: YMKDrivingSession?
А для чего мы сохраняем эту переменную внутри класса? 
Мы же ее потом никак не используем и всегда переназначаем

2021-04-01 10:16 UTC, DCrow commented on example/lib/examples/router_page.dart
> +                      await _controller.addPolyline(_route);
Так можно же внутри setState() вызвать?

2021-04-01 21:01 UTC, ILAgent commented on android/src/main/java/com/unact/yandexmapkit/YandexDrivingRouterImpl.java
> +                new DrivingRouteListener() {
>Тут получается какой-то замаскированный асинхронный метод(со стороны java), хотя он должен быть синхронным и ничего не ожидать от внешних апи.

А чем это плохо? В джаве нет async/await, поэтому там лиснеры. А в дарте есть, так почему бы не смапить джавовое апи с лиснерами на асинхронный метод дарта?

2021-04-01 21:05 UTC, ILAgent commented on example/lib/examples/router_page.dart
> +                      await _controller.addPolyline(_route);
Зачем? Внутри setState() имеет смысл вызывать код, который меняет стейт.

2021-04-01 21:06 UTC, ILAgent commented on ios/Classes/YandexDrivingRouter.swift
> +    private var session: YMKDrivingSession?
Если сессию соберёт GC, то мы не получим результат.

2021-04-01 21:07 UTC, ILAgent commented on ios/Classes/YandexDrivingRouter.swift
> +        router = router ?? YMKDirections.sharedInstance().createDrivingRouter()
Не знаю почему, он это виснет, если вызывать в конструкторе.

2021-04-01 21:10 UTC, ILAgent commented
> форматирование поправить, по аналогии с другими файлами соответствующих языков.

А в каком месте неотформатировано? Вроде бы применял форматирование везде.

2021-04-02 07:53 UTC, DCrow commented on android/src/main/java/com/unact/yandexmapkit/YandexDrivingRouterImpl.java
> +                new DrivingRouteListener() {
Тут дело не в том, что java не поддерживает async/await, а в том что методы этого listener вообще могут быть не вызваны.

По сути эти методы слушают какие-то ивенты, которые будет отправлены внутри `drivingRouter.requestRoutes`.
В случае если метод никак не ответит, у нас получается мертвый кусок кода, который блокирует кусок памяти, а это все может быстро разрастись и привести к тому, что памяти не будет хватать, и в итоге к крешу приложения.
Кроме того плохо иметь разные имплементации одних и тех же действий(в данном случае это различие с YandexSearchHandlerImpl). 
Это в дальнейшем и усложняет поддержку, и начинает путать других пользователей либы, которые видят это впервые.

И если уже говорить про dart, то в данном случае это больше метод принимающий коллбэки и в последствии вызывающий их.

2021-04-02 08:06 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +        router = router ?? YMKDirections.sharedInstance().createDrivingRouter()
Действительно виснет, давай тогда комментарий оставим, почему так именно было сделано

2021-04-02 08:08 UTC, DCrow commented on ios/Classes/YandexDrivingRouter.swift
> +    private var session: YMKDrivingSession?
Не совсем понял почему GC ее должен собрать.
В текущей реализации внутри этого метода остаются референсы к переменной `result`, которая находится в коллбэке, а он в свою очередь находится внутри сессии, что не должно давать GC помечать их на удаление.

2021-04-02 08:11 UTC, DCrow commented on example/lib/examples/router_page.dart
> +                      await _controller.addPolyline(_route);
Действительно, флаттер советует только изменения в интерфейсе писать в setState, то пусть остается.
Мне лично казалось, что так читабельность кода выше.

2021-04-02 08:13 UTC, DCrow commented
В Java например в проекте используются отступы в 2 пробела, а тут 4. И в swift аналогично.
В целом это не критично, хочется одного рода читабельность поддерживать.

2021-04-02 19:53 UTC, ILAgent commented on ios/Classes/YandexDrivingRouter.swift
> +    private var session: YMKDrivingSession?
В том-то и дел, что колбек внутри сессии, а сессию если не держать, то она соберётся вместе с колбеком.

2021-05-26 14:10 UTC, closed without merging

2021-05-30 09:22 UTC, DmitriyIgnashchenko commented
жаль, нужная штука

2021-06-01 08:06 UTC, ILAgent commented
@DmitriyIgnashchenko увы нет времени на допиливание пр( Можете использовать мой форк при необходимости.

2021-06-02 18:41 UTC, DmitriyIgnashchenko commented
Спасибо большое за труд